apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-wildcard-cert
  namespace: kube-system
spec:
  dnsNames:
  - '*.ucdialplans.com'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: letsencrypt-wildcard-cert