k8sServiceHost: 127.0.0.1
k8sServicePort: 6444
routingMode: native
ipv4NativeRoutingCIDR: 10.0.0.0/9
autoDirectNodeRoutes: true
tunnel: disabled
bpf:
  hostRouting: true
  masquerade: true
ipam:
  mode: kubernetes
  operator:
    clusterPoolIPv4PodCIDRList: 
    - 10.42.0.0/16
k8sClientRateLimit:
  qps: 5
  burst: 10
cluster:
  name: cloud
  id: 1
operator: 
  replicas: 1
l2announcements:
  enabled: true
  leaseDuration: 30s
  leaseRenewDeadline: 10s
  leaseRetryPeriod: 4s
externalIPs:
  enabled: true
kubeProxyReplacement: true
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
    service:
      annotations:
        tailscale.com/expose: 'true'
        tailscale.com/hostname: 'cloud-hubble'     

gatewayAPI:
  enabled: true
  secretsNamespace:
    create: false
    name: kube-system
    sync: true   