k8sServiceHost: 10.0.0.101
k8sServicePort: 6443
ipam:
  operator:
    clusterPoolIPv4PodCIDRList: 
    - 10.42.0.0/16
k8sClientRateLimit:
  qps: 5
  burst: 10
cluster:
  name: cloud
  id: 2
l2announcements:
  enabled: true
  leaseDuration: 30s
  leaseRenewDeadline: 10s
  leaseRetryPeriod: 4s
externalIPs:
  enabled: true
kubeProxyReplacement: true
hubble:
  relay:
    enabled: true
  ui:
    enabled: true