---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: akeyless
  namespace: external-secrets
spec:
  provider:
    akeyless:
      akeylessGWApiURL: "https://api.akeyless.io"
      authSecretRef:
        secretRef:
          accessID:
            name: akeyless-apikey
            key: accessId
            namespace: external-secrets
          accessType:
            name: akeyless-apikey
            key: accessType
            namespace: external-secrets
          accessTypeParam:
            name: akeyless-apikey
            key: accessTypeParam
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical
  namespace: external-secrets
spec:
  provider:
    infisical:
      hostAPI: https://app.infisical.com
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: external-secrets
            name: infisical-credentials
          clientSecret:
            key: clientSecret
            namespace: external-secrets
            name: infisical-credentials
      secretsScope:
        projectSlug: kubernetes-mxww
        environmentSlug: home
        recursive: true
