apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: nightly-backups
  namespace: longhorn
spec:
  cron: "0 5 * * *"
  task: backup
  groups:
  - default
  retain: 7
  concurrency: 5
  labels:
    job: nightly-backups

---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: 24-hour-snapshots
  namespace: longhorn
spec:
  cron: "0 17 * * ?"
  task: snapshot
  groups:
  - daily-snapshot
  retain: 2
  concurrency: 2
  labels:
    job: 24-hour-snapshots

---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: filesystem-trim
  namespace: longhorn
spec:
  cron: "0 1 * * ?"
  task: filesystem-trim
  groups:
  - default
  retain: 2
  concurrency: 2
  labels:
    job: filesystem-trim