apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promstack
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: "https://prometheus-community.github.io/helm-charts"
    targetRevision: 72.9.0
    chart: kube-prometheus-stack
    helm:
      valueFiles:
      - $values/manifests/monitoring/promstack/promstack-values.yaml
  - repoURL: "git@github.com:kenlasko/k8s-cloud.git"
    ref: values
  - repoURL: "git@github.com:kenlasko/k8s-cloud.git"
    path: manifests/monitoring/promstack
    directory:
      recurse: true
    targetRevision: HEAD
    directory:
      exclude: "*_DISABLED.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true