kind: deployment
schedule: "30 */2 * * *"  # Every hour at 30 min past
deschedulerPolicy:
  strategies:
    RemoveDuplicates:
      enabled: true
    RemovePodsHavingTooManyRestarts:
      enabled: true
      params:
        podsHavingTooManyRestarts:
          podRestartThreshold: 10
          includingInitContainers: true