---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-secrets
  namespace: monitoring
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: alertmanager-secrets
  dataFrom:
  - extract:
      key: /alertmanager
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  data:
  - secretKey: smtp_auth_username
    remoteRef:
      key: /email/smtp2go
      property: username
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: smtp_auth_password
    remoteRef:
      key: /email/smtp2go
      property: password
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None