---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: grafana-admin
  dataFrom:
  - extract:
      key: /grafana
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None