---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: kube-system
spec:
  encryptedData:
    api-token: AgA3slyDvLqycwyTflyUbDpkbxA8YXcxxMf5JTPaLv+jG+RItjVX3i9tD0AZXWRThEhu2cegUnG2iARDm1gsLmlkqvpRXuDW1TZkvFCsqIoGxqouIrCjmoB2l5K8GPkYU7NtChUdXR6xximKIlCiPh9wu7cxqZs0XGuDLg3zTiKxn9uwHqDXgwGAtp5V8rSuhchrAqGaJY97ga747IOA+UgWQXg0IRmuLBFzik7begD9BAZe8KWW/sIJy9O/IpSGyRPIfUYQTFMsj837X1Gi83535fZ8nCxZ4TSefTOKiCLrZvyyKTHfxgFJS24vKlPuDEvgM/wZ9pwxhKmx2zDunmXv5LRpSaQnHcinMGv8e8ZZxD7wpR8hQzeKnTe0Vq3s80WKV2fGq7gGv04IQVRC1eteUdmEo1iMlvUVf9vPPRF9WcuYv/zkobzsAw1QFgED8F/OOQApZdj7EsmM3w2LwG7CuhoW/b5Fv8BO/aqI2v41K4ByzHCSzVx1cQ3b+RNsn3OqPxE/RBI/j9eGMeCXMHG0wfkq0nkAzv32vt4K3wto7SN1hcorAcHuujCg/oxonwg0aCetXMhdunEdkh+x8hfK4a3mpakDUoqyJJfMuFWSuFw2MbXdYi5l6sX+mJhnJ54u7RVSdnrwLzAxGEsHriCUZjZExrZmeeN9Kt666NlnGzgIgcjQXhTNDGATIgB6Q1/E1UDOc6A4EmHC3Sx8kGVAGCn/MYRlPibUuqA7A7qIwWcbHuiYYZUo
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: kube-system
    type: kubernetes.io/opaque