---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mariadb-backup
  namespace: mariadb
spec:
  schedule: "00 5 * * *"  # Start at 1am every day
  suspend: true
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - rpi1
          containers:
          - name: mariadb-backup
            image: mariadb:11.4.4
            imagePullPolicy: IfNotPresent
            env: 
            - name: K3S_ROOT_PW 
              valueFrom: 
                secretKeyRef: 
                  name: mariadb-passwords
                  key: mariadb-root-password
            command: 
            - /bin/sh
            - -c
            - echo "$(date +%F_%T) Backing up MariaDB user accounts and privileges..." &&
              mysql -B -N -h mariadb.mariadb.svc.cluster.local -uroot -p$K3S_ROOT_PW -e "SELECT CONCAT('\'', user,'\'@\'', host, '\'') FROM user WHERE user != 'debian-sys-maint' AND user != 'root' AND user != ''" mysql > mariadb-users.txt &&
              while read line; do mysql -B -N -h mariadb.mariadb.svc.cluster.local -uroot -p$K3S_ROOT_PW -e "SHOW GRANTS FOR $line"; done < mariadb-users.txt > /app/mariadb-users.sql &&
              sed -i 's/$/;/' /app/mariadb-users.sql &&
              echo "$(date +%F_%T) Backing up MariaDB databases..." && 
              mysqldump -h mariadb.mariadb.svc.cluster.local -u root -p$K3S_ROOT_PW -B homeassist phpmyadmin ucdialplans vaultwarden > /app/mariadb-backup.sql && 
              echo "$(date +%F_%T) MariaDB databases have been backed up. Zipping contents..." && 
              gzip -f /app/mariadb-backup.sql && 
              echo "$(date +%F_%T) Finished!"
            volumeMounts:
            - name: data
              mountPath: /app
          restartPolicy: Never #OnFailure
          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: db-backup-pvc

