---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-backup-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/kube-storage/mariadb-backup"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - rpi1

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-backup-pvc
  namespace: mariadb
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi


