---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mariadb-ucdialplans-statupdate
  namespace: mariadb
spec:
  schedule: "0 */2 * * *"  # Once every 2 hours
  suspend: true
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          nodeSelector:
            server-type: rpi
          containers:
          - name: mariadb-ucdialplans-statusupdate
            image: docker.io/mariadb:11.6.2
            imagePullPolicy: IfNotPresent
            env: 
            - name: K3S_ROOT_PW 
              valueFrom: 
                secretKeyRef: 
                  name: mariadb 
                  key: mariadb-root-password
            command: 
            - /bin/sh
            - -c
            - echo "$(date +%F_%T) Updating UCDialplans.com statistics..." &&
              mysql -B -N -h mariadb.mariadb.svc.cluster.local -P 3306 -uroot -p$K3S_ROOT_PW -e "call ucdialplans.InfoCache_Update()" ucdialplans &&
              echo "$(date +%F_%T) Finished!"
          restartPolicy: Never