---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ucdialplans
  namespace: ucdialplans
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ucdialplans
  template:
    metadata:
      labels:
        app: ucdialplans
        name: ucdialplans
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: dockerhub-kenlasko-creds
      containers:
      - name: ucdialplans
        image: kenlasko/ucdialplans:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
              - all
        resources:
          requests:
            cpu: 1000m
            memory: 1200Mi
          limits:
            cpu: 1000m
            memory: 1200Mi
        volumeMounts:
        - name: ucdialplans-webconfig
          mountPath: /var/www/web.config
          subPath: web.config
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
      automountServiceAccountToken: false
      volumes:
        - configMap:
            items:
            - key: web.config
              path: web.config
            name: ucdialplans-webconfig
          name: ucdialplans-webconfig
