apiVersion: v1
kind: Service
metadata:
  labels:
    app: ucdialplans-service
  name: ucdialplans-service
  namespace: ucdialplans
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: web
  selector:
    app: ucdialplans