apiVersion: v1
kind: Service
metadata:
  name: keel-frontend
  namespace: kube-system
  labels:
    app: keel
    tailscale.com/proxy-class: "enable-tun"
  annotations:
    tailscale.com/expose: 'true'
    tailscale.com/hostname: 'cloud-keel'
    omni-kube-service-exposer.sidero.dev/port: "50105"
    omni-kube-service-exposer.sidero.dev/label: Keel
    omni-kube-service-exposer.sidero.dev/icon: |
      H4sICE0LJ2YAA2suc3ZnAEWQ0W6DMAxF3/cVVvZs4yQkJBPwsD+hXdZUC1AVRvr5C0XqpCtdH+va
      ltwu2wUeY5qWTsR1vX1UVc6Zsqb5fqkUM1clIWC7hvw5PzrBwGDrIgFhGk4p4Gk4/1zu8+/01Ykp
      ZPhP9O1tWCOU/qgVqDNKS8Y6YNQMUlOt1V5pXg6AJxzCVwtfgAdoHi2xtFDXZNgldOS1R6nIWouK
      vCrHyFu5eWrYRDQF9IbK71PxICnJG5OKKSnxoNiQ0zY9iT3spmsoe410IBtipyI21Hgj4PuaUife
      ZXAuGFH17f6n/u0PkrcaBlABAAA=
spec:
  type: ClusterIP
  ports:
  - port: 9300
    protocol: TCP
    targetPort: 9300
    name: web
  selector:
    app: keel
