apiVersion: v1
kind: Service
metadata:
  labels:
    app: keel
  name: keel-frontend
  namespace: keel
spec:
  type: ClusterIP
  ports:
  - port: 9300
    protocol: TCP
    targetPort: 9300
    name: web
  selector:
    app: keel
