image:
  repository: grewhit25/keel-arm64
  tag: latest

polling:
  enabled: true
  defaultSchedule: "0 */4 * * *" # Every 4 hours

helmProvider:
  enabled: false

secret:
  name: keel-creds
  create: false

mail:
  enabled: true
  from: "Keel Cloud Updates <keelupdates@ucdialplans.com>"
  to: "ken.lasko@gmail.com"
  smtp:
    server: "smtp.sendgrid.net"
    port: 587
    user: "apikey"

basicauth:
  enabled: true
  user: "kenadmin"

persistence:
  enabled: true
  storageClass: "local-path"
  size: 1Gi

serviceAnnotations:
  omni-kube-service-exposer.sidero.dev/port: "50105"
  omni-kube-service-exposer.sidero.dev/label: Keel
  omni-kube-service-exposer.sidero.dev/icon: |
    H4sICE0LJ2YAA2suc3ZnAEWQ0W6DMAxF3/cVVvZs4yQkJBPwsD+hXdZUC1AVRvr5C0XqpCtdH+va
    ltwu2wUeY5qWTsR1vX1UVc6Zsqb5fqkUM1clIWC7hvw5PzrBwGDrIgFhGk4p4Gk4/1zu8+/01Ykp
    ZPhP9O1tWCOU/qgVqDNKS8Y6YNQMUlOt1V5pXg6AJxzCVwtfgAdoHi2xtFDXZNgldOS1R6nIWouK
    vCrHyFu5eWrYRDQF9IbK71PxICnJG5OKKSnxoNiQ0zY9iT3spmsoe410IBtipyI21Hgj4PuaUife
    ZXAuGFH17f6n/u0PkrcaBlABAAA=