apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# resources:
#   - service.yaml
patches:
  - target:
      kind: Service
      name: headlamp
    patch: |-
      metadata:
        labels:
          tailscale.com/proxy-class: "enable-tun"
        annotations:
          tailscale.com/expose: 'true'
          tailscale.com/hostname: 'cloud-headlamp'