apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://charts.jetstack.io'
    targetRevision: "*"
    chart: cert-manager
    helm:
      valueFiles:
      - $values/cert-manager/values.yaml
  - repoURL: 'git@github.com:kenlasko/k3s-cloud.git'
    ref: values
  - repoURL: 'git@github.com:kenlasko/k3s-cloud.git'
    path: cert-manager
    targetRevision: HEAD
    directory:
      exclude: '*_DISABLED.yaml'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      null #temporarily disabled for vacation
    syncOptions:
    - CreateNamespace=true
