apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: "https://charts.jetstack.io"
    targetRevision: v1.17.1
    chart: cert-manager
    helm:
      valueFiles:
      - $values/manifests/cert-manager/values.yaml
  - repoURL: "git@github.com:kenlasko/k8s-cloud.git"
    ref: values
  - repoURL: "git@github.com:kenlasko/k8s-cloud.git"
    path: manifests/cert-manager
    targetRevision: HEAD
    directory:
      exclude: "*_DISABLED.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
