apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: "https://helm.cilium.io/"
    targetRevision: 1.17.0
    chart: cilium
    helm:
      valueFiles:
      - $values/cilium/values.yaml
  - repoURL: "git@github.com:kenlasko/k8s-cloud.git"
    ref: values
  - repoURL: "git@github.com:kenlasko/k8s-cloud.git"
    path: cilium
    targetRevision: HEAD
    directory:
      exclude: "*_DISABLED.yaml"
  - repoURL: "https://github.com/kubernetes-sigs/gateway-api.git"
    path: "config/crd/experimental"
    targetRevision: "v1.2.1"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cilium
  ignoreDifferences:
  - jsonPointers:
    - /data/ca.crt
    kind: ConfigMap
    name: hubble-ca-cert
  - jsonPointers:
    - /data/ca.crt
    - /data/tls.crt
    - /data/tls.key
    kind: Secret
    name: hubble-relay-client-certs
  - jsonPointers:
    - /data/ca.crt
    - /data/tls.crt
    - /data/tls.key
    kind: Secret
    name: hubble-server-certs
  - jsonPointers:
    - /data/ca.crt
    - /data/ca.key
    kind: Secret
    name: cilium-ca
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true