apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: "https://headlamp-k8s.github.io/headlamp/"
    targetRevision: 0.28.1
    chart: headlamp
    helm:
      valueFiles:
      - $values/headlamp/values.yaml
  - repoURL: "git@github.com:kenlasko/k8s-cloud.git"
    ref: values
  - repoURL: "git@github.com:kenlasko/k8s-cloud.git"
    path: manifests/headlamp
    targetRevision: HEAD
    directory:
      exclude: "*_DISABLED.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: headlamp
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
