apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://headlamp-k8s.github.io/headlamp/'
    targetRevision: "*"
    chart: headlamp
    helm:
      valueFiles:
      - $values/headlamp/values.yaml
  - repoURL: 'git@github.com:kenlasko/k3s-cloud.git'
    ref: values
  - repoURL: 'git@github.com:kenlasko/k3s-cloud.git'
    path: headlamp
    targetRevision: HEAD
  patches:
    - target:
        kind: Service
        name: headlamp # Replace with your service name
      patch: |
        apiVersion: v1
        kind: Service
        metadata:
          annotations:
            tailscale.com/expose: 'true'
            tailscale.com/hostname: 'cloud-headlamp'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: headlamp
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
