apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keel
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://charts.keel.sh'
    targetRevision: "*"
    chart: keel
    helm:
      valueFiles:
      - $values/keel/values.yaml
  - repoURL: 'git@github.com:kenlasko/k3s-cloud.git'
    ref: values
  - repoURL: 'git@github.com:kenlasko/k3s-cloud.git'
    path: keel
    targetRevision: HEAD
    directory:
      exclude: '*_DISABLED.yaml'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true