apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubelet-serving-cert-approver
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    repoURL: "https://github.com/alex1989hu/kubelet-serving-cert-approver.git"
    path: "deploy"
    directory:
      include: "standalone-install.yaml"
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubelet-serving-cert-approver
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: restricted
        pod-security.kubernetes.io/enforce-version: latest
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true