apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: localpath
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/rancher/local-path-provisioner'
    path: deploy
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true