apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  sources:
  - repoURL: 'https://charts.longhorn.io'
    targetRevision: 1.5.*
    chart: longhorn
    helm:
      valueFiles:
      - $values/longhorn/values.yaml
  - repoURL: 'git@github.com:kenlasko/k3s-cloud.git'
    ref: values
  - repoURL: 'git@github.com:kenlasko/k3s-cloud.git'
    path: longhorn
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: longhorn
  syncPolicy:
    syncOptions:
    - CreateNamespace=true