apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: "registry-1.docker.io/bitnamicharts"
    targetRevision: 20.2.2
    chart: mariadb
    helm:
      valueFiles:
      - $values/manifests/mariadb/values.yaml
  - repoURL: "git@github.com:kenlasko/k8s-cloud.git"
    ref: values
  - repoURL: "git@github.com:kenlasko/k8s-cloud.git"
    path: manifests/mariadb
    targetRevision: HEAD
    directory:
      exclude: "*_DISABLED.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: mariadb
  ignoreDifferences:
  - jsonPointers:
    - /spec/externalName
    kind: Service
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
