apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 19.1.0
    chart: mariadb
    helm:
      valueFiles:
      - $values/mariadb/values.yaml
  - repoURL: 'git@github.com:kenlasko/k3s-cloud.git'
    ref: values
  - repoURL: 'git@github.com:kenlasko/k3s-cloud.git'
    path: mariadb
    targetRevision: HEAD
    directory:
      exclude: '*_DISABLED.yaml'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mariadb
  ignoreDifferences:
  - jsonPointers:
    - /spec/externalName
    kind: Service
  syncPolicy:
    automated:
      null #temporarily disabled for vacation
    syncOptions:
    - CreateNamespace=true
