apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: 'https://metallb.github.io/metallb'
    targetRevision: "*"
    chart: metallb
    helm:
      valueFiles:
      - $values/metallb/values.yaml
  - repoURL: 'git@github.com:kenlasko/k3s-cloud.git'
    ref: values
  - repoURL: 'git@github.com:kenlasko/k3s-cloud.git'
    path: metallb
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metallb-system
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /spec/conversion/webhook/clientConfig
  syncPolicy:
    syncOptions:
    - CreateNamespace=true