apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smarter-device-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
  - repoURL: 'https://geek-cookbook.github.io/charts/'
    targetRevision: "*"
    chart: smarter-device-manager
    helm:
      valueFiles:
      - $values/smarter-device-manager/values.yaml
  - repoURL: 'git@github.com:kenlasko/K3S.git'
    ref: values
  - repoURL: 'git@github.com:kenlasko/K3S.git'
    path: smarter-device-manager
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
