apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://pkgs.tailscale.com/helmcharts'
    targetRevision: 1.68.1 #"*"
    chart: tailscale-operator
    helm:
      valueFiles:
      - $values/tailscale/values.yaml
  - repoURL: 'git@github.com:kenlasko/k3s-cloud.git'
    ref: values
  - repoURL: 'git@github.com:kenlasko/k3s-cloud.git'
    path: tailscale
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tailscale
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true