apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ucdialplans
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:kenlasko/k3s-cloud.git'
    path: ucdialplans
    targetRevision: HEAD
    directory:
      exclude: '*_DISABLED.yaml'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ucdialplans
  syncPolicy:
    automated:
      null #temporarily disabled for vacation
    syncOptions:
    - CreateNamespace=true