apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ucdialplans
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'git@github.com:kenlasko/k3s-cloud.git'
    path: ucdialplans
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ucdialplans
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true