apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://k3rnelpan1c-dev.github.io/uptime-kuma-helm/'
    targetRevision: "*"
    chart: uptime-kuma
    helm:
      valueFiles:
      - $values/uptime-kuma/values.yaml
  - repoURL: 'git@github.com:kenlasko/k3s-cloud.git'
    ref: values
  - repoURL: 'git@github.com:kenlasko/k3s-cloud.git'
    path: uptime-kuma
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: uptime-kuma
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true