apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: "https://k3rnelpan1c-dev.github.io/uptime-kuma-helm/"
    targetRevision: 1.4.0
    chart: uptime-kuma
    helm:
      valueFiles:
      - $values/uptime-kuma/values.yaml
  - repoURL: "git@github.com:kenlasko/k8s-cloud.git"
    ref: values
  - repoURL: "git@github.com:kenlasko/k8s-cloud.git"
    path: manifests/uptime-kuma
    targetRevision: HEAD
    directory:
      exclude: "*_DISABLED.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: uptime-kuma
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true