apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-vaultwarden-pvc
  namespace: vaultwarden
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-high-value
  resources:
    requests:
      storage: 250Mi
