apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-pvc
  namespace: vaultwarden
spec:
  storageClassName: local-path
  resources:
    requests:
      storage: 250Mi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/kube-storage"
