---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kured
  namespace: kube-system
spec:
  encryptedData:
    notifyUrl: AgBZ9WOUNGGFqFc5v/mSV8+Z23KF2TK168w1VY8tDvn/+clGZ5rtyUiXnZoKIhJTmpv6os5z0OQdC4jR2LKSfZDaE3Q+yOHQokaG8hhHQjQPGDmXnTTXwAEBDOTXWLsnbPSrMndWgoC6V30J5Htkc1TxJnIBez8Wf2a2tjYdmspd6imYXbMfWvXstVaKm0qeR219h25Vh2u5GV9DutW2FfsKndxXgXh5RlGf4M9v6IWSVxYpgAp6qtD1WxCIpdNuEdVBtCfzw1ylE9DYglnjBHwyOTmZAHsKpW/GBVP3yBGRIBSH7AYcit6R3a+4jThhfo/wIKNfJ4CHVYmXl6TgIQruQGZsVtNnWLOw/1+lr8PNrIPeDYDtDhQ8CtXtviWm6HIz6TSOMakmkXlpnBEzafsASfPdne+brtrffSop/yZHcsLVp5RbbDWLktYKIrYTuydpiRWs0bOWi9qR1rwvtEpiIg9exKp25hrvI/mAyhqQJYNiXyMOPCX/NWu0wHdr7cSix7jFMeWFOjYGXNv3nX2j2BeDzysPylfxn6nsOynRr22K+UJAYfKiC+Ix17WKdg37xD1ZApr9aLGQ+3LP/rGJvNy0RbsRmX7dLM7WEmUVAStxCal9MUjba/DN1SeaI8RBa8dJuc0oqrFFYO+K+N+Mw4H4Fkn5V9gg3Zlr0adtYZ/nTnLhX4pUbz3y8MN3yUq9dScihExaJCGbQMs8W14bcwhsyzF2eryYGB+oe2UZkif66EdM7Jri8niKiwC+J1mpT7Hxg3EECqhgz7NKjomqmuO301bZ0kw3mIREaW+QopSO2JDptDEal3FXygPWuMMFqVtHrC0b4+ztEi+2AooqDZJlrUKGIdnrMNh20MqMhCDp3iRDAn7DiknrL0n/xXV2k2JK4E6jW5ejzEWq9gpm3zlaJ94SFonBzeuiag==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kured
      name: kured
      namespace: kube-system
    type: Opaque
