apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco-security
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: "https://falcosecurity.github.io/charts"
    targetRevision: 4.19.0
    chart: falco
    helm:
      valueFiles:
      - $values/falco-security/values.yaml
  - repoURL: "git@github.com:kenlasko/k8s-cloud.git"
    ref: values
  - repoURL: "git@github.com:kenlasko/k8s-cloud.git"
    path: falco-security
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: falco
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
