apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keel
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: "https://charts.keel.sh"
    targetRevision: 1.0.5
    chart: keel
    helm:
      valueFiles:
      - $values/keel/values.yaml
  - repoURL: "git@github.com:kenlasko/k8s-cloud.git"
    ref: values
  - repoURL: "git@github.com:kenlasko/k8s-cloud.git"
    path: manifests/keel
    targetRevision: HEAD
    directory:
      exclude: "*_DISABLED.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true