apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: phpmyadmin
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: "registry-1.docker.io/bitnamicharts"
    targetRevision: 18.1.2
    chart: phpmyadmin
    helm:
      valueFiles:
      - $values/phpmyadmin/values.yaml
  - repoURL: "git@github.com:kenlasko/k8s-cloud.git"
    ref: values
  - repoURL: "git@github.com:kenlasko/k8s-cloud.git"
    path: phpmyadmin
    targetRevision: HEAD
    directory:
      exclude: "*_DISABLED.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: mariadb
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
