apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "git@github.com:kenlasko/k8s-cloud.git"
    path: manifests/registry
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: registry
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
