apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-upgrade-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:kenlasko/k3s-cloud.git'
    path: system-upgrade-controller
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: system-upgrade
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
