apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: "https://pkgs.tailscale.com/helmcharts"
    targetRevision: 1.82.0
    chart: tailscale-operator
    helm:
      valueFiles:
      - $values/manifests/network/tailscale/values.yaml
  - repoURL: "git@github.com:kenlasko/k8s-cloud.git"
    ref: values
  - repoURL: "git@github.com:kenlasko/k8s-cloud.git"
    path: manifests/network/tailscale
    targetRevision: HEAD
    directory:
      exclude: "*_DISABLED.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: tailscale
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true