---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBG3jUha5kd6WWE8BwWDAsDMRcsSrhK8/1qlxl7an3ldaUcrGqgmdtlulngi/RRjhk3PIPm7zbrwyF7GD+iw9eYTp+EQlnaNWbbrh2mmqqAfqbGTXWq2Hv4aUpFlEUo37rTah+PR1pp7Sh/AjtP3F0R3Lk2fJI8EKSQXp35oIE44VYqmvjrvHBU+sFbU9rkXW857A4RqR10KuarRWmsz+V8dM7HW7bIuv2n1ZmleyLOrVoukSKGyP50YUym2PtH2e1RfDO1DYYx7mMnfSEvHQhmpF/IY7hhp1j0FyCxE7E8OvhVuF2Q0JrEMiyKHMqlzLs0BmfL5gUXfJ+NA4GcTtuW71xeULVxLPCy7kiO3CoBtw301q5T0IumtnbGLpLvPRQm/GG4MGo5z2nnjPRrj6qLws6SH5p8onbzk91/ZSP02Yrg+0uzpfQELvfbUpkBLkROsTVdcX17pdIrjs/HZh+eIx1UWo9LodFE6zDzJ7/tsJTyBmLlz6DCNeS5OGIYyRWrRfBU/e1n4xbXEAAJMUS/VAcXrzgCHNzXO9IInoiumAG4i+M06V1PFmUjW29ra99uVNosZ1BFwLs/fbLExQdN28H59rxUAvwDoT4Gxq62W1A8LMWzeHqmZnb6GVL1kSIF529goVrJGjCCZbbPC6xK3puX4V9v2wsvhbVkLDlcahucKAqihb+XDFt6UxpT8ny+nJPlGTdTVZAYfE0=
    client_secret: AgCXR8U8tOwfjH5bmqyuFjNOrsJZLhmIJSug7AxXGCDqjA30m8r3gMio81ml+YEBMooCEtYi3LB4onwxoKkAr3GDoyZ0+RzxK+TC/iFKUA+IlovHxJm9NTKq/65PVyf1Djme9wNOJFmqXFQU+u6OpS/C7yvZEG5enJl1m9WifE2Iol2jANfC8PXbKuVOBPQK1xH1uXbwMdUj4xsZvjhHiJtMSRdpXRgGmeqvnsfa6nyhNQZy50rsheoG3ZLwEtNNjmdIABrdIzkks8orivnioZCOzROb7krQIx00hJAZYtmmdyusm1rPV2erKUdVTQZ8YzVFFgLZYgt4K0clhMpiGaA3XQKzvCwkLU4zfUsyn5ZQmwPI/CxhPy6QiYU+keUF4Xlj69LlucDVErND9PA5nJ9ce8VQDZa2ugXnkfJa+3siA26rDE4UgnNUTFzsfhSeV3EaZF6BKplysALiK/80xlK8rn0/d+vcBKbnipd1wgOT9ZyKHi9JvOqqlbildsJ/rkINrYPnkSh3zNErrldzMKoEm8bYRljKbiHTXAFkLRY1VuPxUW4DUSHr6EK3sZglfsWGDo8JWjMGE4aDmmFJ8zsFw165/MVyprY79MOuqnjdRK5uK9+YSTxaNAGtSBAiJu2WGtk4Xme4SfY7I4eYDYSZBhOf2NpMOlban13kyxIAGisZq3jyDvYiY4EQMvKsGRbIbISAZ4plUcJvlshF1NslhLyj62JMPDb5SZoEch2dxMxpx8qiT01r/pPiM/uLQNpRiKUB45NpuslnBg==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: tailscale-operator
      name: operator-oauth
      namespace: tailscale
    type: Opaque
