apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: 7.8.24
    chart: argo-cd
    helm:
      valueFiles:
      - $values/manifests/argocd/values.yaml
  - repoURL: 'git@github.com:kenlasko/k8s-cloud.git'
    ref: values
  - repoURL: 'git@github.com:kenlasko/k8s-cloud.git'
    path: manifests/argocd
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
