apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://cloud-argocd.ucdialplans.com
  admin.enabled: "false"
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: $github-auth-secrets:dex.github.clientID
          clientSecret: $github-auth-secrets:dex.github.clientSecret
  repositories: |
    - url: git@github.com:kenlasko/k8s-cloud.git
      sshPrivateKeySecret:
        name: github-k3s-private-key
        key: privateKey
    - url: git@github.com:kenlasko/helm-charts.git
      sshPrivateKeySecret:
        name: github-helm-private-key
        key: privateKey
  resource.exclusions: |
    - apiGroups:
        - cilium.io
      kinds:
        - CiliumIdentity
      clusters:
        - "*"