---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    slack-token: AgBLnR+tk04MfUkWbxr1ASBl8bt9uoCdleRyFD5nxSFc8xY6F2+HCaiWdNfgS9Fhwbt0Xnd1trRVFXX2gaJpYIjhr6dDYhr4hEpMQbTabHTk0giRHGWcLCjTR/0LHZ7Hf/hYkORYbXb2SPuf+P3Wq30kcjChRbXAfO2OLQCvSRqmdhErjScO4mIOJcnBAFbiiwj8Z+enHVHtHBumaVFdmkwqqZ/BKzbON5ZKvTnM89g5yFWV19iUthcG0wtbMwkr/gNvc4J+8rBzvophBuHLugSNZFZOtA1FqY0Teuy1jnsukIKY5zqk5G/StTRdAm9HOIqD90+xJSi6WvMDIxFau+srDkdbLHrBlX3ZeZswUt9KNzkv9oc3MQaaONUk+N5mrU4R3XoeLNHlDMIhPtsdiOeNsHm8LLKh/JEJahe0QWg5aWfGnHsrlDKR+jiqDrRmSDD0jeR1U2dpqFIY9JcfuXUZgOYld92xOjIiY87DzAQlG1hDj85JVTSJkj87DVQS+ceSRYpmycgTYHr0FdYhZ/zzdTgQILGr1IyPO0Tzo9E2vuDJciXyRfBMSfLcklJ4YLEP7Qsz+mYIwcKxbeGb5lH5rDkBc2RRVkM8XlD7Uzj640xAMI3m1xpJ1O/hPXfhvdZdnPVd08+5e6+xjQm2DEKFQkRCT8I0PT/xYh01xBLzKw9IFSFLTcdCyCUiGX21pZJL9aWu5FhgMFlI16TAfv14d9E/gDY5rMWLZ9/m7Y2W651zJcp2J7LC3ElyQitDUIuq9jLAe0z7BEg=
  template:
    metadata:
      creationTimestamp: null
      name: argocd-notifications-secret
      namespace: argocd
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-auth-secrets
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  encryptedData:
    dex.github.clientID: AgBn2FDQNfZcCPwoFQ9tibGSPspKK1ZbxTGKu3IjgUvY35SSUibjabj4ClFtDHq2RKBIyt2DFULVNjX2NhkPAJ2OzNYnPf3UWruC5NldyT0AuhU9tpphBMZh2QHq86sSxm+lRdPh92qwDBdSL046JhIDDbtJVpz6lMEdVdLy201/fyT3V9scyhD7Wad61uLYyurZqpWQFyfYuWBs54sLADkPi7nIcIevxyDtgCKwCrYzyQ/V/eIesV6QLa6VlKW7lxWHHG50OyCwlLjpdqxPXiAXfteL4C7pQY5wzqP8uI+uUZh9EcBV+yquaciixD7Yqyc6mtY5g/XOG8zAu+D0A1DrjP3GoA2YoXcHSRTNzntrhyfX2C18DKjWyUQfVcyMwP7KZ9caWk2GGV+YJvdDGhT5tNr7WWjWAbK4aLIBJwJ3jfLqSKTrCMHZb94ErQtvlFdMO4ccPWwEiAqdC9v9tHC4qEU1ibji+t13up/t1lKVpm0f4r0upnGkOa1e9N72V+CLW4yxtotQh+78OS9rgBWficOEkDAysx27Z3hLzsfOJy6f+GLKUCFRHbGxmCwYOooh6am0fvDqQMvAFTm4+fUzD2miYXJrIjRFmn59IqutVcy99wLw6kC0Q9A6XRIux71DHi3pQediVRYr5sQzNS9ejo57JY//qPZlHaDZL+5BCcZPAvT3wl9G41JR6wmUvnSieWFV0ZXv0Je76P7Anpg9Kiwuuw==
    dex.github.clientSecret: AgCHv9+FzBoLjrLWLciFZ2jwt/FrXOBYo9jyvZ7Hll9/7FPNEncK8xQW7qn0Ton/CDltzlJPy6LlqddNIBkED5eIv5VF44XHKvvVZParhdwl0KIJbYgTy9Ady8zn1NUBsgLn0KVYN0JU92e3dNkFO7ocaGUd1wcW7mBKapEHsN6H1wsVwmwKyquINL2fIiU4KctrAG4zBIFv9WEby8Fg1NzUrq4aFXb/VD95EXT+M6eWzHw+ASMTQ1JmzvBONymUKhwfe6A0H71NKUJMm0MH4Rp6893MUi6ZNqWZhNbRXcTlIKeuPLgLGB0m1FpgvYC5x98OIqNx1o6SgORwUMZQD2yiza+1M7Bu8Sb8gLRrqu7gi/CspxiYOf+QnYOnoBR/jMIk7mccOptWeRSrDRYjm4vYFSRmOnSLdmjPOUj4/4su1/CME/VeqGj4CUI6u727WVV6RnZax05iJFcSNI6/VOSZtKz1Q6iVxW2mP0ljHPXny0kUaJyLb12grQyqt0DlENPdBu5GWzZGiQFZHxHbMZdKlWdbUvQ8bbsP3rh4RxPsthfk7D6qTx3TVWcSn2M2utGCl5DTH4icgvpIpZI+Mf3w68WeLsmfRdoHmNR+k+hLS2vk09KUuiLZbYyDuhYa+dps2DEcftwrC6igX9NQ+FCkSDOCTChct9SEX1hImOyNeK0k1955XmsvSujXCvcP3CmNZprKboQvxeYP/rX7m0YNZej/Kqt6e3rm3RIWuUMpexWU2RHaLM5l
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: argocd
      name: github-auth-secrets
      namespace: argocd
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: k8s-repo
  namespace: argocd
spec:
  encryptedData:
    sshPrivateKey: AgAGZg9ccY900JiC3i3dFIl9WTdGFw10XT3PoqAvfMQu0ap7aQH9l7ylWe6L55QFuNfSFuUijTWw4IzaDNsCC15bllrZSy4LMU8ZIjBNxzWtEEgjuHwFZIT49bfra3pG9zuyST+97vuZkf6pFoip8XXl7gR57u4/opyAdpkdskrSNVWB9maPOA2zAoFk6KqVwzeniyu44vjoDWHrSJxu6UEbmZPOr2Yw3i9f7hv8ZYG26Rgnleu9VO+PG/XQm2UXyLHumnpTWBbAZpRS2qoMDmjVbN3z2BkAx4fU09TDa7HorburdOg5weoxQOxL7j+8bdwVH7r2ROkgH4zNX1ZTdyvIBCm+cPurk5bUMhGITX+uYuKkvXwfWsb0S/LtTm0DqfP29tZIHBZGW1NCD7o1N7fad/cgWNtNHq6sUFYignMCgU9Wgb7xKQLLCAB/ZUMrt+QkC712nTP+TJsTUeVUv2Hiw6XDlC3uI8Gez+IeEvG/Nmz207nMk85q6aw3YCxFWqejNVGadu0aO6kJWhUsD2JETmCF8Fw9Nsir2Qz7150o4VfKmvyRn6G/YFR8olcdCyvedDDIae/h+AHSNDM8azDcPg6lVmmNVk9uNPHjnUeajgpPzcE/Pxs4RLmNDVaoV8vDDMBYhvTuQfywDNKXh7q70UWBVnYm8FfrqScJN/XnlMqXtpYRsDhapcW78zVSJTI4knoadrBRjyktEMZVNScVJ73TY1XglztlH0uUJ++g03CPnolTBn1EEAfognLMmkLX3jpiEQA05kG4WQeZ3bqLuwYWBEJzZGz+4R9jwLt4HZu1ms0mSNu3tRMopPFQSbTINxJEpFr0RJAsEpCljBBWy59ecDgq2P5kiT/z1f5yxdrBHvYVZds5u14krkPnUZdKBP+m9cwdchN4p+Imd3+oBkeDT/GgtcZX/HTon5lF2e6qKqPCLr49kbagcHBJRah6emJmoW2gMldaAvX7aw9qmbf5K9WRNmKd7g5/4bY950PX9feuj87nwBY+t0tiUhG8cKmWmIMw40/TWqijHOp1ZiF0lXfovCyNj29kORezRYUGlZrJ8+lwhk1u6kgslgudIninOx9IFTUwZBhyGffXJbuGzLtd3w/tNyhn+orkdWVcf48hlykO2KZPw07zKmOKX4Yx+hl6Rs7Do5uS6hLYwmj1bKGh1fBYhkztRSr8qFpY1EDtOL2qiUUlDB+hm6ZR/1D1+kC0W2rjgV/O8uvZIkkqZUwj/4JPrDM=
    type: AgA3n5e1w7dQ0WRTMst2tmdqfSTOiPCzx3sHJEA7QlY+ncNXcBWCASl14Vf2ITbMaeqebzTF26Z5paIGc/qRx4hHQgvht9CG4wGUrQABStAxa2XWXkr8DJGoGvu8jCDg6sED0siZrpXfeJKw/B+GH/8L/4kpcJEkuhZRdnFPy6Z+jgK8zSC64QZ1A84KlzuIuufVAZRrbBoNbiCp9g7+q8OvAlOONqQzfIyZMmAmWGTLqe1t3HML1sm48wrHb+cNHp/vQqyRHcuR6KFeiEGo+QAe1GRiNy49JRo8EwBt2gpZyevFehZTlVQ37nJjdk14cE058TB1LY7kYXgk754JGKOhmMwykOTv99VzWjk3i8Xl1OV0a7xCqSOdO3HVUEPjdnR8SP4vkzo0SD+vF3OzTgCvpg1O9X5hqWu5/ZY2AWAMqgvu/B1/E9/wk9QSTIOdpR4K6oHK03xPJEz1M6gtrmEpQELQgRnFUf3J3Cb7qFHPOdvYU5qqma2ZFwn6Wy612jacBJzzrtkqJ7IcecdnKleDN9CvhqKbfZ39dkyVao2XKnwCIXCPH4TlZYdjNMD55O5Jc9vdNLeLMDoIBESxGQHih7JnEeqTL1mU4xNcI0rV+37dTkBG3h/AYxJJfbcKuNp/yYUl0TIaVM6GPGcAAJgSJFM//VzdcApKh10yCoVXiA3eG/PkFCcYeyB0abZinW//Rrg=
    url: AgChn+WjPlQDpzpmTzVOHXoUclRAuOkFaeu4v6dbZ6hmbU0MhYtRBf6xdXuPukwRsn1EIVKFCLq+QK01KhHs3MyCeTndvaDihxhdpYE+oLgRNT1wWa7/P1UpKf97MyxHx0M+9SBJ4T/LccK+12JMRWBUYzzuEGjTDPd1D293a8nI+1yUv9AVfuJ3Kmy7pelYloOn5xUnhBfuVlFe+PzkQcHfdJ3PDhwfOPsytAA7WTwiRK5ERB3FBy0ZRN7H4NubwBloyBaHRYBUEP03MYn11lSOLKF7+YUnv1IPoiLEU0rizKsoErdYYtsd6C+3A+1XSTeub3/nd8aL3IqNvTO7/z6RwuCAKBcPmckoniDfcH5crXLKmNmuOXJWQ9JBE9H6cGQ2AUDL/8r0ieaFlAwzSNWZ/HigurAVk6Y3njGuVUMmtnha6DDB7TYICbiD3Ux9qMuhaCk5/EatJXk1AsIR+HqqsTLn89rCW4zlE1y2ZN2zXkoMRTPUAgEcpWaJCTwiz9bVBn+zjIU+27IFF7bStRRHiKOI11qqM5XbdeGe87qB06TT7+kcH7xcqLIOkC50advZapM9uewIhFmjFd3T8Hq/yJl6UXryNKe6wUTfo73fUET6Z+Ultsi4FO3bluf4znm5Q7NRWOCNXfifzU1h20/Zd2OxdQeRO4QWxNhXjEKmSWCAMSsER726D2uXXrSzuyw7Ns7cILc1B0YQx5gDiBlDo2y9tgbAUp588HxqjCEC7Pnks9op
  template:
    metadata:
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: k8s-repo
      namespace: argocd
