driver:
  kind: modern-bpf
collectors:
  enabled: true
  docker:
    enabled: false
  crio:
    enabled: false
  containerd:
    enabled: true
    socket: /run/k3s/containerd/containerd.sock
  kubernetes:
    enabled: true
  
customRules:
  custom-rules.yaml: |-
    - rule: Contact K8S API Server From Container
      exceptions:
      - name: allowed_to_contact_api_server
        fields: [k8s.ns.name, container.name, proc.name] 
        comps: [=,=,=]
        values:
        - [argocd, application-controller, argocd-applicat]
        - [argocd, applicationset-controller, argocd-applicat]
        - [argocd, notifications-controller, argocd-notifica]
        - [argocd, repo-server, git]
        - [argocd, server, argocd-server]
        - [cert-manager, cert-manager-webhook, webhook]
        - [cloudflare, cloudflare-tunnel, cloudflared]
        - [external-dns, external-dns, external-dns]
        - [headlamp, headlamp, headlamp-server]
        - [media-tools, backup-media-apps, kubectl]
        - [monitoring, grafana-sc-dashboard, python]
        - [monitoring, grafana-sc-datasources, python]
        - [monitoring, prometheus, prometheus]
        - [netdata, netdata, curl]
        - [netdata, sd, agent_sd]
        - [portainer, portainer, portainer]
        - [system-upgrade, system-upgrade-controller, system-upgrade-]
        - [tailscale, operator, operator]
        - [tailscale, tailscale, tailscaled]
      override:
        exceptions: append

    - rule: Clear Log Activities
      exceptions:
      - name: allowed_to_clear
        fields: [container.name, proc.pname, proc.name] 
        comps: [=,=,=]
        values:
        - [host, k3s-agent, containerd]
        - [host, k3s-server, containerd]
      override:
        exceptions: append

    - rule: Redirect STDOUT/STDIN to Network Connection in Container
      exceptions:
      - name: allowed_to_do_stdout_stdin
        fields: [k8s.ns.name, container.name, proc.name] 
        comps: [=,=,in]
        values:
        - [argocd, repo-server, [argocd-repo-ser, git]]
        - [gitea, gitea, [git]]
      override:
        exceptions: append

    - rule: Run shell untrusted
      exceptions:
      - name: allowed_shell
        fields: [k8s.ns.name, container.name, proc.pname] 
        comps: [=,=,in]
        values:
        - [mariadb, mariadb-galera, [mysqld]]
      override:
        exceptions: append

falcosidekick:
  enabled: true

  webui:
    enabled: true
    existingSecret: sidekick-creds

    redis:
      enabled: true