---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: admin-token
  namespace: cloudflare
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: admin-token
  data:
  - secretKey: token 
    remoteRef:
      key: /cloudflare/admin-token
