---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: admin-token
  namespace: cloudflare
spec:
  encryptedData:
    token: AgCUF1VgQPKNDtNbqmPS753o8ybxe1Dm73AQlTJrZ1ZSZmAj1RLU0E3N99D6/xSemcbdL2lHuV639eoRhHxFU4pPwXpY88cysJBpCR31W3jLuH/2WK4JTCMrFcPrRqQk5n7/V00qc+8yssB3tlmaUBULuXB/Cbv7DEu2I8TeQRkztZQbo8kaUjFYPrlU/mTGFYTwghs/cMcFyAv7GCaY2k1psyKoujEJYf0bBPR16gvP8KXWq/Dj94ImHJcS1qWG9WJZEDVy4x8jbffWavcgY8D5BgtjnwUeU8vGFLqbA7U0y9mKWJD+pr17TVpNw9D6CZ4D94pai58Q14ie6lLC8aTC9b2a7Z1HD9O0Iod8y91htw5o9FKJPy9ut3r4Jbk50UQrczI2pgXUu1kwIlgFY4P5ZDrjrzdGLfvi54ThE16X5P2kbqlLKGJz9kB2oTUO+C1rFQTFCDoE6FS6fSgxWITlIu3+dzx7gGas9J/jA0b0fwtgBeIpP2ZSF36vYRuN2xeekQoMggm1hTAZ2F5WWPRA1DDs/yVJ2Lx0ldrl4Mj2fVy6Cw0kxMUuyG33YXSGG14JH5hc4s+ZrkrWgEZteB+FBm6TcUDkOBrE6rA+J1ehIRKgzf1A0zhEteWZudWtEMGytsWoayOiC/E5ViDlRW4r9tX08QCssKV8uqqnZEo0SvfKV+F3cxdBD8KvSWhEkrfGxiOJ8yylYenqDEbCoGHDQIk/Avl8X1G443ho5OUWvdtU0grp8IfiCnxzXOQJaVqHMCNZhCQA47eTz5DsneuVvyoaoVkfL2Zpjmr4rNc1y84PeFvvlDZVUmyT1i5ePzd1dGY7X+kba/ZJhAn2Xve+L3JFTqTuRaZ/mrRIGWFY3E4BOzo1ATVdYT7up7Cc7dXenAEXt5tfmOwiKrjbk92eI2yOkqdlFBTxvp0Sq8Ntm76JwmC3M3lI
  template:
    metadata:
      creationTimestamp: null
      name: admin-token
      namespace: cloudflare
    type: Opaque
