---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: admin-token
  namespace: cloudflare
spec:
  encryptedData:
    token: AgA8STJvUAS3fclVVyG0NSQ4HSQWMco2oRb85wPNwLMQ5nVNesPrxVZ8hR3/wz3oJhfBKGG1V5eWBfb4BTrZf7kDMHX8SFycYfQ55712Iw6UYfFHpZ6pwNcWrHzHggl2ZfQXy9RL5B6XJhcKx9jix88/f6ZnGoBxLQ2CvDR0isJhccgE9dJ850D5fbZxoWh+IkiEDSkJqhhtdS4Kd8kzDzqGslY6b1fk0r3mxniaWERYrQ+diauRunkb/5cXezUE1QsqswquZyBfiyq72uTT16UeT8iwxhw7KAR9pzD6RTHOVJ6iFwDR1BCpW8J2FvbDttlvLzhQK3LhtJAsthRBsvlfT3/5WA5+Na0/SG54gKIqDPAONojLQtWbA+4t5FHgbiEB6d6GfZrf++1bz1XKqXDhSxgvcYkl0RGhSwuSngss5ULOi2MwKS3uYQ6uq9QdZNc+P73JUcPVX6ZitL1rVQGhXVIJeX1erMFehxiAVwIBTuRF2ScQpXpUm5GErt4gJToZNfKd/VO7Pxtoj8LhJP+PERMph2RDHMBXOUKLoB5s6q+IuQEN6EcWNlWFX7megyhOffRjgSTXe4lSHUpnZiPnrVr3YJ2hr0xI6yM5PHVMEHI9y/+2ZLbVwgeNQ9bBLxIRlDNzuVp9YxrAp4bU41VCiKfgQKol0nX5tYfcVUsZ5NAeL5w5BSx/hiQWDzt4hyMpzdZSZUELSZ4xXZIo2BrCNwx15GH4vSwJeU7Aqp0cIa1LPhEQam+5jf8VXHu3ZAjPuLwauNhrNZ5VSsyNO0QrCvQl2SMT407v7HG9tC8ANqaDOJbUDRSzimKLIICRBzSnqvGd9H5hlhS/uuqO9hTKlQG2NsQdfaR3gZy2Ii7DKLKERNo6RAiJZK5H+hbSi4336J8Kq1zzEEtFodId0bBMiChvwvM2AzX4rRsYkArYe8FPjKkbIQre
  template:
    metadata:
      creationTimestamp: null
      name: admin-token
      namespace: cloudflare
