apiVersion: v1
kind: Service
metadata:
  labels:
    app: adguard
  name: adguard-web
  namespace: adguard
spec:
  type: ClusterIP
  ports:
  - name: adguard-web
    port: 3000
    protocol: TCP
    targetPort: http
  selector:
    app: adguard

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: adguard
  name: adguard-dns
  namespace: adguard
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: 10.0.0.153
  ports:
  - name: dns-tls-853
    nodePort: 32700
    port: 853
    protocol: TCP
    targetPort: dns-tls-853
  selector:
    app: adguard