apiVersion: v1
kind: Service
metadata:
  name: adguard-web
  namespace: adguard
  labels:
    app: adguard
    tailscale.com/proxy-class: "enable-tun"
  annotations:
    tailscale.com/expose: 'true'
    tailscale.com/hostname: 'cloud-adguard'
spec:
  type: ClusterIP
  ports:
  - name: adguard-web
    port: 3000
    protocol: TCP
    targetPort: http
  selector:
    app: adguard

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: adguard
  name: adguard-dns
  namespace: adguard
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: 10.0.0.171
  ports:
  - name: dns-tls-853
    nodePort: 32700
    port: 853
    protocol: TCP
    targetPort: dns-tls-853
  selector:
    app: adguard