---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: cloudflare
spec:
  retentionPolicy: "2d"
  configuration:
    endpointURL: "https://fa831d805d821b7c4627b464a9845a9d.r2.cloudflarestorage.com/"
    destinationPath: "s3://postgresql"
    wal:
      compression: gzip
      maxParallel: 4
    data:
      compression: gzip
    s3Credentials:
      accessKeyId:
        name: cloudflare-s3-backup-postgresql
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: cloudflare-s3-backup-postgresql
        key: AWS_SECRET_ACCESS_KEY

---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: oracle
spec:
  retentionPolicy: "2d"
  configuration:
    endpointURL: "https://yzimm6ocyme1.compat.objectstorage.ca-toronto-1.oraclecloud.com/"
    destinationPath: "s3://postgresql"
    wal:
      compression: gzip
      maxParallel: 4
    data:
      compression: gzip
    s3Credentials:
      accessKeyId:
        name: oracle-s3-backup-postgresql
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: oracle-s3-backup-postgresql
        key: AWS_SECRET_ACCESS_KEY

---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: nas01
spec:
  retentionPolicy: "2d"
  configuration:
    endpointURL: "http://nas01.ucdialplans.com:8010"
    destinationPath: "s3://postgresql"
    wal:
      compression: gzip
      maxParallel: 4
    data:
      compression: gzip
    s3Credentials:
      accessKeyId:
        name: nas01-s3-backup-postgresql
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: nas01-s3-backup-postgresql
        key: AWS_SECRET_ACCESS_KEY