apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cloud
  namespace: postgresql
spec:
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.5-v0.3.0
  instances: 1
  bootstrap:
    pg_basebackup:
      source: home-postgresql
  replica:
    enabled: true
    source: home-postgresql
  storage:
    storageClass: local-path
    size: 15Gi

  # # This should be uncommented if you ever need to use this cluster to restore the primary
  # # cluster. It will backup to Cloudflare S3 storage, which can then be used by the primary 
  # # cluster to restore.
  # backup:
  #   retentionPolicy: "7d"
  #   barmanObjectStore:
  #     endpointURL: "https://fa831d805d821b7c4627b464a9845a9d.r2.cloudflarestorage.com/"
  #     destinationPath: "s3://postgresql"
  #     wal:
  #       compression: gzip
  #     s3Credentials:
  #       accessKeyId:
  #         name: cloudflare-s3-backup-postgresql
  #         key: AWS_ACCESS_KEY_ID
  #       secretAccessKey:
  #         name: cloudflare-s3-backup-postgresql
  #         key: AWS_SECRET_ACCESS_KEY
  enableSuperuserAccess: true
  superuserSecret:
    name: postgresql-superuser
  certificates:
    serverAltDNSNames:
    - "home-postgresql.tailb7050.ts.net"
    - "home-postgresql"
    - "home-postgresql.svc.cluster.local"
  managed:
    services:
      additional:
      - selectorType: rw
        updateStrategy: patch
        serviceTemplate:
          metadata:
            name: "postgresql-service"
            annotations:
              tailscale.com/expose: 'true'
              tailscale.com/hostname: 'cloud-postgresql'
          spec:
            type: ClusterIP
  externalClusters:
  - name: home-postgresql
    connectionParameters:
      host: home-postgresql
      user: streaming_replica
      sslmode: verify-full
      dbname: postgres
    sslKey:
      name: replication-certs
      key: tls.key
    sslCert:
      name: replication-certs
      key: tls.crt
    sslRootCert:
      name: replication-certs
      key: ca.crt