apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: "https://cloudnative-pg.github.io/charts"
    targetRevision: 0.24.0
    chart: cloudnative-pg
    helm:
      valueFiles:
      - $values/manifests/database/postgresql/values.yaml
  - repoURL: "git@github.com:kenlasko/k8s-cloud.git"
    ref: values
  - repoURL: "git@github.com:kenlasko/k8s-cloud.git"
    path: manifests/database/postgresql
    targetRevision: HEAD
    directory:
      exclude: "*_DISABLED.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: postgresql
  ignoreDifferences:
  - jsonPointers:
    - /spec/externalName
    kind: Service
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: restricted
        pod-security.kubernetes.io/enforce-version: latest
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
