apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://releases.rancher.com/server-charts/latest'
    targetRevision: 2.*
    chart: rancher
    helm:
      valueFiles:
      - $values/rancher/values.yaml
  - repoURL: 'git@github.com:kenlasko/cloud-k3s.git'
    ref: values
  - repoURL: 'git@github.com:kenlasko/cloud-k3s.git'
    path: rancher
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: rancher
  syncPolicy:
    automated:
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
