---
apiVersion: v1
kind: ConfigMap
metadata:
  name: syslog-ng-config
  namespace: monitoring
data:
  syslog-ng.conf: |
    @version: 3.38

    template t_file { template("${YEAR}-${MONTH}-${DAY} ${HOUR}:${MIN}:${SEC} ${LEVEL} ${MSGHDR}${MSG}\n"); };

    source s_network_udp { syslog(transport(udp) port(5514)); };

    destination d_loki { syslog("loki-promtail-syslog" transport("tcp") port(1514)); };
    destination d_mesg { file("/var/log/messages" template(t_file)); };

    log {
      source(s_network_udp);
      destination(d_loki); destination(d_mesg);
    };

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syslog-ng
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syslog-ng
  template:
    metadata:
      labels:
        app: syslog-ng
        name: syslog-ng
    spec:
      restartPolicy: Always
      automountServiceAccountToken: false
      volumes:
      - name: config
        configMap:
          name: syslog-ng-config
      containers:
      - name: syslog-ng
        image: linuxserver/syslog-ng
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
        volumeMounts:
        - name: config
          mountPath: "/config/syslog-ng.conf"
          subPath: "syslog-ng.conf"
