# apiVersion: v1
# kind: Service
# metadata:
#   name: adguard-web
#   namespace: adguard
#   labels:
#     app: adguard
#     tailscale.com/proxy-class: "enable-tun"
#   annotations:
#     tailscale.com/expose: 'true'
#     tailscale.com/hostname: 'cloud-adguard'
# spec:
#   type: ClusterIP
#   ports:
#   - name: adguard-web
#     port: 3000
#     protocol: TCP
#     targetPort: http
#   selector:
#     app: adguard

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: adguard
  name: adguard-dns
  namespace: adguard
spec:
  type: ClusterIP
  ports:
  # - name: dns-tcp
  #   port: 53
  #   protocol: TCP
  #   targetPort: dns-tcp
  # - name: dns-udp
  #   port: 53
  #   protocol: UDP
  #   targetPort: dns-udp
  - name: dns-tls-853
    port: 853
    protocol: TCP
    targetPort: dns-tls-853
  selector:
    app: adguard