image:
  repository: adguard/adguardhome
  tag: v0.107.57
  registry: docker.io
priorityClassName: medium-priority
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  seccompProfile:
    type: RuntimeDefault
env:
- name: TZ
  value: "America/Toronto"
resources:
  requests:
    cpu: 60m
    memory: 150Mi
  limits:
    # cpu: 2000m
    memory: 250Mi
livenessProbe:
  failureThreshold: 10
  httpGet:
    path: /login.html
    port: http
    scheme: HTTP
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /login.html
    port: http
    scheme: HTTP
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
extraVolumes:
- name: adguard-conf
  persistentVolumeClaim:
    claimName: adguard-conf
- name: adguard-work
  persistentVolumeClaim:
    claimName: adguard-work
- name: dns-wildcard-cert
  secret:
    secretName: letsencrypt-dns-wildcard-cert
extraVolumeMounts:
- name: adguard-conf
  mountPath: /opt/adguardhome/conf
- name: adguard-work
  mountPath: /opt/adguardhome/work
- name: dns-wildcard-cert
  mountPath: /etc/certs
service:
  port: 3000
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "cloud-adguard"
  extraLabels:
    tailscale.com/proxy-class: "enable-tun"
extraPorts:
- port: 853
  name: dns-tls-853
  protocol: TCP
tailscale:
  name: cloud-adguard-egress
httpRouteNameOverride: cloud-adguard.ucdialplans.com