---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-webhook
  namespace: external-dns
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: adguard-webhook
  template:
    metadata:
      labels:
        app: adguard-webhook
    spec:
      restartPolicy: Always
      serviceAccountName: external-dns
      containers:
      - name: adguardhome-webhook
        image:  ghcr.io/muhlba91/external-dns-provider-adguard:v8.0.1
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 100
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            cpu: 20m
            memory: 10Mi
          limits:
            # cpu: 150m
            memory: 20Mi
        ports:
          - containerPort: 8888
            name: http
        # livenessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: http
        #   initialDelaySeconds: 10
        #   timeoutSeconds: 5
        # readinessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: http
        #   initialDelaySeconds: 10
        #   timeoutSeconds: 5
        env:
        - name: SERVER_HOST
          value: "0.0.0.0" 
        - name: DRY_RUN
          value: "false" 
        - name: LOG_LEVEL
          value: debug
        - name: ADGUARD_URL
          value: "http://cloud-egress-adguard.external-dns.svc.cluster.local:3000/control/" # Note: URL should be in the format of http://adguard.home:3000/control/
        - name: ADGUARD_USER
          valueFrom:
            secretKeyRef:
              name: adguard-creds
              key: username
        - name: ADGUARD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: adguard-creds
              key: password
      securityContext:
        fsGroup: 65534 # For ExternalDNS to be able to read Kubernetes token files