---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: external-dns
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      restartPolicy: Always
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.15.1
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 100
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            cpu: 2m
            memory: 40Mi
          limits:
            # cpu: 100m
            memory: 80Mi
        env:
        - name: TZ
          value: "America/Toronto"
        envFrom:
        - secretRef:
            name: adguard-creds
        args:
        - --txt-owner-id=cloud
        - --source=service
        - --source=gateway-httproute
        - --source=gateway-tlsroute
        - --source=gateway-tcproute
        - --source=gateway-udproute
        - --provider=webhook
        - --webhook-provider-url=http://localhost:8888
        - --annotation-filter=external-dns.alpha.kubernetes.io/exclude notin (true)
      - name: adguardhome-webhook
        image:  ghcr.io/muhlba91/external-dns-provider-adguard:v8.0.0
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 100
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            cpu: 20m
            memory: 10Mi
          limits:
            # cpu: 150m
            memory: 20Mi
        ports:
          - containerPort: 8888
            name: http
        # livenessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: http
        #   initialDelaySeconds: 10
        #   timeoutSeconds: 5
        # readinessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: http
        #   initialDelaySeconds: 10
        #   timeoutSeconds: 5
        env:
        - name: SERVER_HOST
          value: "0.0.0.0" 
        - name: DRY_RUN
          value: "false" 
        - name: LOG_LEVEL
          value: debug
        - name: ADGUARD_URL
          value: "http://cloud-egress-adguard.external-dns.svc.cluster.local:3000/control/" # Note: URL should be in the format of http://adguard.home:3000/control/
        - name: ADGUARD_USER
          valueFrom:
            secretKeyRef:
              name: adguard-creds
              key: username
        - name: ADGUARD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: adguard-creds
              key: password
      securityContext:
        fsGroup: 65534 # For ExternalDNS to be able to read Kubernetes token files