policy: sync
sources:
- service
- gateway-httproute
txtOwnerId: cloud
extraArgs:
- --webhook-provider-url=http://localhost:8888
- --annotation-filter=external-dns.alpha.kubernetes.io/exclude notin (true)
provider:
  name: webhook
  webhook:
    image:  
      repository: ghcr.io/muhlba91/external-dns-provider-adguard
      tag: v8.0.1
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 100
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop: ["ALL"]
    resources:
      requests:
        cpu: 2m
        memory: 10Mi
      limits:
        # cpu: 100m
        memory: 20Mi
    env:
    - name: SERVER_HOST
      value: "0.0.0.0" 
    - name: DRY_RUN
      value: "false" 
    - name: LOG_LEVEL
      value: info
    - name: ADGUARD_URL
      value: "http://cloud-egress-adguard.external-dns.svc.cluster.local:3000/control/"
    - name: ADGUARD_USER
      valueFrom:
        secretKeyRef:
          name: adguard-creds
          key: username
    - name: ADGUARD_PASSWORD
      valueFrom:
        secretKeyRef:
          name: adguard-creds
          key: password
