---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-k3s-private-key
  namespace: argocd
spec:
  encryptedData:
    privateKey: AgBOSXjNvaVwpEPyXbsPRU08q30125OqbT3tSNFSjR2RJjlbdVQiyiSaWeJBCIVzgvT/wrx7vPLpY3mgAQ5ps4uzV0MDMBfX5FyVYa4Pef5Q5CJSHfZemzxM35Z8EsmUmW2wWCWoqmvqfV5mi50Ja2XMn3I7F6OGz4U4oDTMa2uoSe9PyGQ4hBgetmJtNqGHFGQOyvlk3KoQFZej7mOj428mfb3o02Q75nBfN76gj7NX0W6ubaf/MAW735OSQKhvppZKl30ZOrvXhGTRqTgj1hh5AqRTHLZ5ba8jEYMDNMSGMB0r1YkMcRCDXwFNSKUj4gKkopilpBDEB5/Iz5rsdTm41ahFmEmzfuzn7BsY/JpVFvY0PBTs9fSTYZD19TTdCRqvBo/VN2rY5hqhOWDPua+QTeNMG/z2q3eDGLmPnTQr8J+YOBZGJBH/QhziENxJ1Jd94y7jc0izqMXB2ckoQSf8rF/Qwkt0u08tsflehyE2BUItZZWI74kq3m8P5sG4GN0XDFQjRUw6damkxNwNLKKkoqm0s49s7X8ZGT0qxRMJypi6tItfRJhMr1OzdraLI9srjeqhOj4n0RLXCQWmJaiYDoZ0JFWUw1VlYSwBMbv+a+vjkyFC/irRKlAWvkCARpL9aZUHBFwtAKLYCnZXcfIJGLvBVZeuYPaBFvoJs5QE6t1Y8u0ttvUIWKfNP9/EyhfwEjXJRgZaXWeuNlU59kb5rgE/OKBGnJhcOytZI/IlZCU4AA7XV/JqIwcuXm0wPPVxXcwK41/G6crRA9sH1zTAACs9VITWRq3Rw7dioTE+Xc7VDzqNOdoeiRtQhSzhljkEZaUuVn/ZUbafh1gXOJ9KyyyKX+TcDlGTlTiOd65Yj//rYQEG9d6+G5f8NWt9ClN9NBUtJ3dUp/gP5c93kMstM1n0m+ZGzNRpmgFq9VEXiCFALbQG2fAsXQVnSQ1CuwGBRuzcLOsZLlLN+eBbo3GLn2cSWMIWXr5RXMjDeqhRKHOupXXfy6R/ZkCXsxUoBNW6UiaCqHZdhoXRwM7I79RwZNveemMxyXTkCi1x2RPZJCzpO/nmkzBkY0MfRVWRv/tNEL5xcO9bWqlH/WZW4unMNvRooGkDcnn4t0KcA1CJZlWESQgyhAzcrtuM9SBWbi2Mf2hn222w7364a3wseCaDeU1GQ4BCPlEqm82Myk2hLIYPTUMoFnJ5/8S9J6kE/T602ju11rm5hGLeUnNLIHwSMpaQ71ZkdgpzUr8=
  template:
    metadata:
      creationTimestamp: null
      name: github-k3s-private-key
      namespace: argocd
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-helm-private-key
  namespace: argocd
spec:
  encryptedData:
    privateKey: AgBiXzV0sGhRToYPtExmsfRGrSAUKgt0dCpETJA1tT+uo256s/wtbZPZr0Dr55T/+2+MVRI/muFrpqTyb0LJH4Ddf8wvMj8/aOFlWlorJr1+TEo+gzb1go9157B2Dq/qav/2LPbJERLUOZB5sVbQLtlvNeFi2WnEanDZ/VsZ0dfqfMBjE0JXhRqpVwjG58Sv4qZKWaY9gV1g2bcv7hqZ/PjRfh+LTG5NIGdKD1hrj/1plRZ8TGEn5AvxHJRoeglbEGgFnzN9ES5b8iQvJBurbIVAcPWjMgXnhqaA+CmbvacEVGut5+Rp0rbR4nisKeHxE9xgKYXL5V827SwInNPG4CKlCU/AbyBdna4UOv/s9FCENAPija6F1AGayWu8C2kcKGkiWC07DhR8RlXXLRksdm4j+ye8E+93ZEJkb7m29HXHZrx1WGjF4GoBMqrZWRZp5iYzs4JuPr6LAf4dbXyOuZzDZ09ZMW8IaF9/iDHGTnAr1dORIqfTmK1Io6713X47foyWSuMZpV3Toi8BpdlS5+OkKRh7luQ2zu/nJFX9HC0ub5Khrd0oopfjto1c6FO9ZHWxQU4f+XpPpVxNb/nRvCvXXwPr0pJoCVeSrAz9AQKoLjNq/0O09EfWcZrxVrjvO9zWgoISUWy5MUlWcfW7AuZe2QEdCDUN9mtKabGhffeSvGlNhWTG56m0bIp71/U/Zyb7zeFUUbndZUSUANa+cOAW6PAgojl28lRsAN/xoz1Rr4Wfa9G3u2LlntBzn2Rwp4zYVYm1G7pT0k5aR6myOrCCQgfuSZG5rP+oLP8Qg9Ib0leU/qKsTsInvIrnrRhUudfs5JlGzcyJ/Q6SPkoW4eRi6PcwWvFDl62bI9yFswDSPZ6vOXZ4HLlER3wxb+SY+wJA1r58wNUO3ZUGJLS/bnsdURYnoKhepLIqJ36tUxd98z3nD1Mvf+pVFPPPrW2bhuM7HXgX2nHKAYGab/KMzRn61EWxeIZl4mIQzIEYiISi7Rh+hU6dzvT1+25wp7QWhM3CuIC0HsKGIY5EX53WA02XB0+PPs4uvKxBwbYIHH5ixdu6T8QEIS4gqqqsUht+I/oNWXRFRTqYEY7zG5hB+mwhXnQL8/WYZckp2BW7rCc38Mo1QCAc3IkBvn+lEhi96en//GbSwDQpFvojuZz0BJTlb5dxqREE0SfHHEmZ0LIiafBeGbDqefFd0JYBqm9yD5lsMwDEUXv7GYUj94l1kBHy9NPkgYs++cPSuIo=
  template:
    metadata:
      creationTimestamp: null
      name: github-helm-private-key
      namespace: argocd
    type: Opaque