---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-k3s-private-key
  namespace: argocd
spec:
  encryptedData:
    privateKey: AgB0j/iFGRpmvFckfGijTr8/qklKAxFxuIf3YoXTEz23SIfr5VrNzrlYIkCstj+2zrvDLar+NvvukJjXWXQIYztugf9HEAiKgUnHp/CLmz9gMCMmADJQon31CzQn4JyApbwGDBq0XVrP7gAhqc1mCkxy72/x3VCrGSamCsiTIbAOXOVQsTBZjKqV+q3Vist+ZhB1IaMCYBL4p8UY1by76zImVgPoPkS8svtqtrC1nPORN+NEgzkpoPGkBohYusRqzzuJtdjpOQbi96b8D2qK1KTjyO8lWHr/vR538c00VD26143tyyKZ+tWRD2lex4mHihl2JnBShqVWSfyMwxs7ww5+KHKs64LRsSMQ1sNrtHPajwxc90sHPIiBDl4g9rs3X7cneTMDb9QyNEjySubK8g4enZne+CppPWmFBoWj5BsFj0pVDG7lw+kL/X6pMmqjLhiW+22CWp63XxW7TvXJdeOTStelTxQZxJLIA0A/zOBri7RZp4cXU3G9xtR7Z1S5SideBNpFOfLeKIBYZKQRD+u/pMs7sjfHxvtiUVXqw0rUkm67r/7T6vHlOyKVmHB1fqAPkwyKbyYx2KhFI44DTy/iDJo+I5UTnqr+a888OHHUJVhUcAwOWKPx9V2OF4iCYa1zmvmU9q4JNQsArsqMSpmwCdXauXurun15c5l8dU/ouxhHlXVumUKzsG9sHVI5+DLACAvHCKynRH5A+KO2TcmuzdeWpfvtzagkHUVbTNVd07Pu3XRKHiHjJz8CX5sLnyPHnmTNuVEHGjyeRqBMfjxtNjtnLH8Y4+qFNuHJw5wVznyd4jrLZMz3KI+LSnROoYI0sq9jbAXjHCApazmkwzepLNryMxUOTL61DUw0r7N5jmEMr1hVACbrksfmDYqazB+hBD7+aZ6SUlpqSQ6dxJL8lwj0U3BDeA8QvE6mv6yOK5UEgP3Jp9Igd5qa2oZLkG65crcJtNbU26eIH0ojzWzjjD7VB0Rttd6Sa2VBsb6ep4YM5XzXWwCzpNnf+xznDfqVo1J81MOC7fgmdr+qwLYdyCVrfWTsBQK+MSfmUXDg+6vkqgr2ga+2Rx06C/cH8RzsbfurjdgcMObw2ONc5om7WVBcpSNnDK3F2TpF/qVcsH8Ll3qkbX0y9xsvISlpVNIDRJiTjWx1eBavF5XUJfqBS0oU095bnDvi/xx5hYtbB2t+sqMD/XOiee3B95bRxH95JQy+BO1y/+csuOZc5Ldzgkju12lniERKzeE=
  template:
    metadata:
      creationTimestamp: null
      name: github-k3s-private-key
      namespace: argocd
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-helm-private-key
  namespace: argocd
spec:
  encryptedData:
    privateKey: AgAV0WGGTssL3RYzT2V93kiC69rrZstG4g45cwMgnIcGHyzf3tTQ3lA+dmyZ2HM/KsR59C/Q2K5uCM6Bb9nEj91CxPd+3ohq0+WAo5dDZo4hgo78pbZfhNHnf/nxfL+Yr5xIif8E9PN0RXLKbQjYtjFq4yVKz3s5sCh9sUvb61Bg9OvHrMNQ+ZRBD8Xl9Zq5AjEzI6PMA4Bxsv4TOLSwxpUxS7OUQFCm1kgAPJ8BQ3eRCJfGup9DBTLgkPA+fb+PO7prGCAQWUlcc6YRCo046RlaEuUofd6CeQm/qAgaQxGsMCTBUr3qgVxUgj8l4tpwH4s3TsLK4dfGpuUbd7Q3KhWOSOjWjnGSDtp/5pePgxMck/Qf1SVAhHbSYPI2OFs1f1miul8rANsDSvY1tQGMYl6SHwS8aUvSM48uKrMG5Ib0suBWMEUwb+lA8AmqRHtcs1oFRDwI8WYeq3V/+0/RgYfJ3igVv5umtZvvV84eCTPmPLdNBu95XcB12JL7iry3IMyhkkyO0pDP8a2wQR450y3w9Q4zDQt1Y1FOisJUMG2j3ghvndBKMXHIeyVpIEztel0qfsiVxrW/sEJbW5u73ZcvhHQJUlDZ+wUUvcbxYz4ThYA4LZhBOQCVZ9XXYaeI22BxerqAElKA6OGAot8THY1L4zLMUcwRf/1cT5n/VsptMwosalqeiBv/MeDkfbVa4KotFm79B9cBxV6uf5tAaOBeWOmLLe2KVP2JQjDo9BIwe8debjeCpj7Dxta8XpeusgKHoz+Ota2VJVfKOKFwFNH1KNRPgfVOLN0pp2xIr8kNFPdU4cBqHUu667e6gYhFFJ9K0FzW/84nipd2oHmnjxAokVziPd3Y1L8HzwyqCFsKLXEqwwcun+ewf6q8+s/5lFs76idsCCfzbW4DbyfTxk8yjfDNcKL/03SBVPB6ywKaomDicc/+CU4n3r/am7LUKT5uvhFti/xGc3fHATD52ZdYntff7X2LFtzTJ0KN0CWLGqdZ4822M7kVN23gD4I0O72celLUfS7ZgzRBJiK7pWqSmEBA3ehJ2bkFPj2BGciFVySwre/rch3c4Vl21nI+eAPmerJPyBwgjJ94w7n3ydqGi5MQXM3A9CPCGEYzbCoDIGPpOVOwGEgUrYm1ao62lJ4J+J8lbkO/7TpGXQmVy0AKQEanjq+u/F/p37n76zluG8CnqDBfqSK3ZSCPMyeDG6nJoP4kgr3QlI6h558drHSUCJSLkFhr1Nm7QJE=
  template:
    metadata:
      creationTimestamp: null
      name: github-helm-private-key
      namespace: argocd
    type: Opaque
