global:
  networkPolicy:
    create: true
    defaultDenyIngress: true

configs:
  params:
    server.insecure: true
  cm: 
    create: false # Don't create configmap because I do it separately via 02-repoconfig.yaml
  repositories:
    argocd:
      url: https://argoproj.github.io/argo-helm
      name: argocd
      type: helm
    bitnami:
      url: https://charts.bitnami.com/bitnami
      name: bitnami
      type: helm
    cert-manager:
      url: https://charts.jetstack.io
      name: jetstack
      type: helm
    csi:
      url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
      name: csi-driver-smb
      type: helm
    grafana:
      url: https://grafana.github.io/helm-charts
      name: grafana
      type: helm
    intel:
      url: https://intel.github.io/helm-charts/
      name: intel
      type: helm
    keel:
      url: https://charts.keel.sh
      name: keel
      type: helm
    longhorn:
      url: https://charts.longhorn.io
      name: longhorn
      type: helm
    metallb:
      url: https://metallb.github.io/metallb
      name: metallb
      type: helm
    netdata:
      url: https://netdata.github.io/helmchart/
      name: netdata
      type: helm
    pihole:
      url: https://mojo2600.github.io/pihole-kubernetes/
      name: pihole
      type: helm
    portainer:
      url: https://portainer.github.io/k8s/
      name: portainer
      type: helm
    promstack:
      url: https://prometheus-community.github.io/helm-charts
      name: promstack
      type: helm
    rancher:
      url: https://releases.rancher.com/server-charts/latest
      name: rancher
      type: helm
    traefik:
      url: https://helm.traefik.io/traefik
      name: traefik
      type: helm