apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'git@github.com:kenlasko/k3s-cloud.git'
    path: argocd-apps
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
    syncOptions:
    - CreateNamespace=true
