apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'git@github.com:kenlasko/k3s-cloud.git'
    path: argocd-apps
    targetRevision: HEAD
  # - repoURL: 'https://github.com/argoproj-labs/argocd-image-updater'
  #   path: manifests
  #   directory:
  #     recurse: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
