apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: esphome
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: esphome=esphome/esphome:latest
    argocd-image-updater.argoproj.io/esphome.update-strategy: digest
spec:
  project: default
  source:
    repoURL: 'git@github.com:kenlasko/K3S.git'
    path: home-automation/esphome
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: esphome
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
