---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth0-secrets
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: auth0-secrets
  dataFrom:
  - extract:
      key: /argocd/auth0

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: argocd-notifications-secret
  dataFrom:
  - extract:
      key: /argocd/notifications

# ---
# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: github-auth-secrets
#   namespace: argocd
#   labels:
#     app.kubernetes.io/part-of: argocd
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: akeyless
#     kind: ClusterSecretStore
#   target:
#     name: github-auth-secrets
#   dataFrom:
#   - extract:
#       key: /argocd/github-auth

# ---
# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: k8s-repo
#   namespace: argocd
#   labels:
#     argocd.argoproj.io/secret-type: repository
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: akeyless
#     kind: ClusterSecretStore
#   target:
#     name: k8s-repo
#   dataFrom:
#   - extract:
#       key: /argocd/k8s-repo

# ---
# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: redis-credentials
#   namespace: argocd
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: akeyless
#     kind: ClusterSecretStore
#   target:
#     name: redis-credentials
#   data:
#   - secretKey: redis-password
#     remoteRef:
#       key: /redis
#       property: password
