apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: garmin-upload
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:kenlasko/cloud-k3s.git'
    path: garminupload
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: garmin-upload
  syncPolicy:
    automated:
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
