apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassist
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:kenlasko/K3S.git'
    path: home-automation/homeassist
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: homeassist
  syncPolicy:
    syncOptions:
    - CreateNamespace=true