---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  parentRefs:
  - name: tls
    namespace: cilium
    sectionName: https
  hostnames:
  - "cloud-argocd.ucdialplans.com"
  rules:
  - backendRefs:
    - name: argocd-server
      namespace: argocd
      kind: Service
      port: 80  