apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-device-plugins-operator
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://intel.github.io/helm-charts/'
    targetRevision: 0.26.*
    chart: intel-device-plugins-operator
  - repoURL: 'git@github.com:kenlasko/K3S.git'
    path: media-tools/intel-operator/
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media-tools
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-device-plugins-gpu
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://intel.github.io/helm-charts/'
    targetRevision: 0.26.*
    chart: intel-device-plugins-gpu
    helm:
      valueFiles:
      - $values/media-tools/intel-gpu/values.yaml
  - repoURL: 'git@github.com:kenlasko/K3S.git'
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media-tools
  ignoreDifferences:
  - group: "*"
    kind: GpuDevicePlugin
    jsonPointers:
    - /spec/resourceManager
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true