apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeapi-service-account
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:kenlasko/k3s-cloud.git'
    path: kubeapi-service-account
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true