apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeapi-service-account
  namespace: kube-system


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeapi-cluster-role
  namespace: kube-system
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeapi-cluster-role-binding
subjects:
- namespace: kube-system
  kind: ServiceAccount
  name: kubeapi-service-account 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeapi-cluster-role


---
apiVersion: v1
kind: Secret
metadata:
  name: kubeapi-service-account-secret
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: "kubeapi-service-account"
type: kubernetes.io/service-account-token