apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://metallb.github.io/metallb'
    targetRevision: 0.13.9
    chart: metallb
  - repoURL: 'git@github.com:kenlasko/K3S.git'
    path: metallb
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metallb-system
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /spec/conversion/webhook/clientConfig
  syncPolicy:
    syncOptions:
    - CreateNamespace=true