apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: phpmyadmin
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 11.*
    chart: phpmyadmin
    helm:
      valueFiles:
      - $values/phpmyadmin/values.yaml
  - repoURL: 'git@github.com:kenlasko/cloud-k3s.git'
    ref: values
  - repoURL: 'git@github.com:kenlasko/cloud-k3s.git'
    path: phpmyadmin
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mariadb
  syncPolicy:
    automated:
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
