apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://portainer.github.io/k8s/'
    targetRevision: 1.*
    chart: portainer
    helm:
      valueFiles:
      - $values/portainer/values.yaml
  - repoURL: 'git@github.com:kenlasko/K3S.git'
    ref: values
  - repoURL: 'git@github.com:kenlasko/K3S.git'
    path: portainer
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: portainer
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
