apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: readarr
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: readarr=linuxserver/readarr:nightly
    argocd-image-updater.argoproj.io/readarr.update-strategy: digest
spec:
  project: default
  source:
    repoURL: 'git@github.com:kenlasko/K3S.git'
    path: media-tools/readarr
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media-tools
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
