apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transmission
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: transmission=linuxserver/transmission:latest
    argocd-image-updater.argoproj.io/transmission.update-strategy: digest
spec:
  project: default
  source:
    repoURL: 'git@github.com:kenlasko/K3S.git'
    path: media-tools/transmission
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media-tools
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
