global:
  domain: cloud-argocd.ucdialplans.com

server:
  service:
    labels:
      tailscale.com/proxy-class: "enable-tun"
    annotations:
      tailscale.com/expose: 'true'
      tailscale.com/hostname: 'cloud-argocd'

configs:
  secret:
    createSecret: true
  params:
    server.insecure: true
  cm: 
    create: false # Don't create configmap because I do it separately via 02-repoconfig.yaml
  repositories:
    argocd:
      url: https://argoproj.github.io/argo-helm
      name: argocd
      type: helm
    bitnami:
      url: https://charts.bitnami.com/bitnami
      name: bitnami
      type: helm
    bitnami-labs:
      url: https://bitnami-labs.github.io/sealed-secrets/
      name: bitnami-labs
      type: helm
    cert-manager:
      url: https://charts.jetstack.io
      name: jetstack
      type: helm
    cilium:
      url: https://helm.cilium.io/
      name: cilium
      type: helm
    csi:
      url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
      name: csi-driver-smb
      type: helm
    grafana:
      url: https://grafana.github.io/helm-charts
      name: grafana
      type: helm
    headlamp:
      url: https://headlamp-k8s.github.io/headlamp/
      name: headlamp
      type: helm
    intel:
      url: https://intel.github.io/helm-charts/
      name: intel
      type: helm
    keel:
      url: https://charts.keel.sh
      name: keel
      type: helm
    longhorn:
      url: https://charts.longhorn.io
      name: longhorn
      type: helm
    metallb:
      url: https://metallb.github.io/metallb
      name: metallb
      type: helm
    netdata:
      url: https://netdata.github.io/helmchart/
      name: netdata
      type: helm
    nfs:
      url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
      name: nfs-subdir-external-provisioner
      type: helm
    pihole:
      url: https://mojo2600.github.io/pihole-kubernetes/
      name: pihole
      type: helm
    portainer:
      url: https://portainer.github.io/k8s/
      name: portainer
      type: helm
    promstack:
      url: https://prometheus-community.github.io/helm-charts
      name: promstack
      type: helm
    tailscale-operator:
      url: https://jacobcolvin.com/helm-charts
      name: tailscale-operator
      type: helm
    tailscale-relay:
      url: https://charts.visonneau.fr
      name: tailscale
      type: helm
    traefik:
      url: https://helm.traefik.io/traefik
      name: traefik
      type: helm
    uptime-kuma:
      url: https://k3rnelpan1c-dev.github.io/uptime-kuma-helm/
      name: uptime-kuma
      type: helm

