---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-passwords
  namespace: postgresql
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: postgresql-passwords
  data:
  - secretKey: postgresql-admin-pw
    remoteRef:
      key: /postgresql/superuser
      property: password