---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pgadmin
  namespace: postgres
spec:
  parentRefs:
  - name: tls
    namespace: cilium
    sectionName: https
  hostnames:
  - "cloud-pgadmin.ucdialplans.com"
  rules:
  - backendRefs:
    - name: pgadmin-pgadmin4
      namespace: postgres
      kind: Service
      port: 80