---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ts-authkey
  namespace: mariadb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: ts-authkey
  dataFrom:
  - extract:
      key: /tailscale/operator-oauth

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mariadb-passwords
  namespace: mariadb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: mariadb-passwords
  dataFrom:
  - extract:
      key: /mariadb/passwords