---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mariadb-restore
  namespace: mariadb
spec:
  schedule: "@yearly" 
  suspend: true
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            mariadb-client: 'true'
        spec:
          dnsPolicy: ClusterFirstWithHostNet
          automountServiceAccountToken: false
          containers:
          - name: mariadb-backup
            image: mariadb:11.4.3
            imagePullPolicy: IfNotPresent
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              runAsNonRoot: true
              runAsUser: 1001
              runAsGroup: 100
              seccompProfile:
                type: RuntimeDefault
              capabilities:
                drop: ["ALL"]
            resources:
              requests:
                cpu: 50m
                memory: 700Mi
              limits:
                cpu: 1500m
                memory: 1400Mi
            env: 
            - name: MARIADB_ROOT_PW 
              valueFrom: 
                secretKeyRef: 
                  name: mariadb-passwords
                  key: mariadb-root-password
            command: 
            - /bin/sh
            - -c
            - echo "$(date +%F_%T) Dropping existing MariaDB databases..." &&
              DB_LIST=$(tr '\n' ' ' < /app/mariadb-databases.txt) &&
              SQL_CMD=""; for DB in $DB_LIST; do SQL_CMD="$SQL_CMD DROP DATABASE IF EXISTS \`$DB\`;" done &&
              mariadb -h mariadb -u root -p$MARIADB_ROOT_PW -e "$SQL_CMD" &&
              newest_sql_file=$(ls -t /app/*.sql 2>/dev/null | head -n 1) &&
              echo "$(date +%F_%T) Restoring MariaDB databases from $newest_sql_file..." && 
              mariadb -h mariadb -u root -p$MARIADB_ROOT_PW < $newest_sql_file && 
              echo "$(date +%F_%T) MariaDB databases have been restored" &&
              echo "$(date +%F_%T) Restoring users and procedures..." &&
              mariadb -h mariadb -u root -p$MARIADB_ROOT_PW < /app/procedures.sql &&
              mariadb -h mariadb -u root -p$MARIADB_ROOT_PW < /app/mariadb-users.sql &&
              echo "$(date +%F_%T) Finished!"
            volumeMounts:
            - name: data
              mountPath: /app
          restartPolicy: Never
          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: nfs-mariadb-backup

