apiVersion: v1
kind: Service
metadata:
  labels:
    tailscale.com/proxy-class: "enable-tun"
  annotations:
    tailscale.com/tailnet-fqdn: 'home-mariadb.tailb7050.ts.net'
  name: cloud-egress
spec:
  externalName: cloud-egress
  type: ExternalName