apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: 'home-mariadb.tailb7050.ts.net'
  name: cloud-egress
spec:
  externalName: cloud-egress
  type: ExternalName


# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: mariadb
#   annotations:
#     tailscale.com/expose: 'true'
#   name: mariadb-access
#   namespace: mariadb
# spec:
#   type: ClusterIP
#   ports:
#   - port: 3306
#     protocol: TCP
#     targetPort: 3306
#     name: web
#   selector:
#     app: mariadb