---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ts-authkey
  namespace: mariadb
spec:
  encryptedData:
    ts-authkey: AgB4nRPNngFOc/i2LXNPx6+QxBUqbJdLkjvLOs4Z11phYBfwgS9s7m4Ipaia5snpCx/BzfqxeWj+FBeu7P252qSe+bEnQBcRDNV41x/2L+ZauRzMZlx3Y3Yi1JjtFNTwNsTOYa+ebHSb9RMui2uw8kFrMZctw61fE5YXHfRFndaY5PoimBaSIsQUoq1Nw0UN+mK94qqIZRQlLt0i0w5iqZPiFN0nM/BERjhLOb09zvUzZ1c8O5aIDZ0Awz9cYBqu9sT9hG8NFe/6WCyiKiMTkq4WQf4MCJLIQ182fMXZFmeUMo2KF8xgSyUJmeS0XDAW2WGdcHIIUpx19VEa+5Ti+OPKTN4KoWdwTDtJd5gOzKxX4C4fz9Xot5e0nIUoawoW7rf1XGUKqKScfw1a7kpGvAfQT8EX9o2wIWgpPE5Zz5DNYXaDOBdFBphlmfTep5rtlMxEYpOosPUOa06YNcp89lZywtXB4wfRfBzC6YC6qgwbLxgS9LuzBfy9HPZYkvDBYgOtOXfwLuTZyMpikIaYlFF1M91HDkHrtfrFcMuB8qV/WLrPO3Irt3R+hcQ8/RbCfLpFNu5vm7jTYW4CH1e7bSuJ6peZbHiQkrP5zl/Z6Xzh+0VcYU7fCZ/bNcNBFJLbsexmfWbXGMbfEDZybZcijEFjDe7v2XZAVUsIcv+Wu8itVOLHnLoiwcYbs0oNuDVOCrnRjUFI1ZKFl1+or/SopE+J39XPdpNdvHy4Uv+xdU7KAP8ISKF2dTfgVf7l04kZc0zziImmN7Aw+9Y/nodw
  template:
    metadata:
      creationTimestamp: null
      name: ts-authkey
      namespace: mariadb
    type: opaque
