---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ts-authkey
  namespace: mariadb
spec:
  encryptedData:
    ts-authkey: AgARDdIyNKaDZtuaN1oT1iBu24+dXcyoqY9BEnzpQyZ8VL8ZZAkr70ap7jM7oQbjcFEHN+MenQ9SZ2VLS64gitDMOFzRFIsauNV1WX6buphlLC9qKwFeck5zfe9DygQbE3yOB1SBccIXcjctf+r/+pz3eeNk2FoEIQSJnlL3b9San0dDXag0KCGHjaLyctmVkKry6Q2rVliE+jsGnht53zhN+gf9ORiC+00hGEJIKABkkIPJmAzM9R1wCo5sokv7hCdCfodBGvhiM80Udph7YweMnF9ZStNU1S7wnHD/THnDr6jwGZc45LJ+p7ooCEEAaWABm9hXAR+4SHYsFmeiZFAbUyoIvWgj7AJZbF+9r31Zjv4AcI8sRD9XYfcDd6fcT8lLRqQNO7OnK6ysSA/6uVx9qYisblD3GrFlR4uTD6wbJoyyKSgKs4N/s7GJXVzJIY7sMFD7OtixhuF8V51moVD9Gz8elRtu1kZfAHCybANTQPFZAF23JGTdw0a/6594qWxv0oh1gzjxkKu6JY4eo/0CGlLw0RabvqBmcEokVcz+O2lk0PLHn13F87QMEef2WrIvuFttjnjOLm5SKel3bk00/UXmEK7QL/dyQbK54zzdvSSNDeXade5B5M2ywVZDrvZJ7N2bmQqClzY9/yXIgDawoWFkL+jl4nhGroCnWMT9x3VYB0yNHzZTcZSboeFkO0288wKVLn0duwmVdLMfcbaM663xVGU6Ky/BKfnU5B+LHdw2MTLztjSG53dtE1LhkJkrODdxMNjPZ1ZoFAH1
  template:
    metadata:
      creationTimestamp: null
      name: ts-authkey
      namespace: mariadb
    type: opaque