---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ts-authkey
  namespace: mariadb
spec:
  encryptedData:
    ts-authkey: AgA/Ri/+LMACaxTh1MwB2BU1JUYxX5dAxJQwcMrOyfVb4aOQ8Zo71hW8bKGk+EhTx7fVoFAsynrc9W3UiLX7i/DoaqXW2vW490bcHg1NdNVNGurUewuF3NIh0HhSD9uHCGko206Syfi2FzsEcPIvoTdtaAtVM6rbVdIBO0OMdxYEkVPxJAqm9IYrm/xeVUrO/xhL7YXU3EoQi7d99Ym4/oude763er7HFsJqlxJO+HHgUthZis8UZfwvaWpoG1PkXmHccdNXhL//TDtZijiLzl28P4obJpRGO8LRhZR3N1yGmkN7iq0KMAKVRH/7lxObzz1OhAajL4V855swlsvAITPXF6GqcUSYQ7xMUh/cf24Tnh90H148IeL4sr42iVqcqTIgpSSW4JvkPzIiVYQObufJd75VvRVQfTb9L1oVDhcUCyzCoEeXukyIF+IWlERYDJPd8giwsS0u4Gg1UNL9RGjCO8VTQVUWIiiEF0ZpgAaPhv+cvn3cel9QnaM2tlfCY5KsyLLjVjesuXoyEt6jKj8ep7dq+jqQL7jz4yzR0ULT3z6cnl57QadFYh8JhvoCHO9/3Pt3gwFcfcW2Lrte9Qcpxwp/4lH0UdEvG1VAFk9FZnbBCMsdeHKd4PAlAIEOUl7/sBRJGOpo2MC1OpPXYNmwCJWcqjM5TZaboUiXjBlux6MXh99RWTtPRF8JN2H2ydgOxD0aJrxHjzVFeUE6ZPQH8KQs7AMEsXxYwhuTqSRtFFD2NnQweMtB6eqG3BPO7rpLg4mUMZnBOb8=
  template:
    metadata:
      creationTimestamp: null
      name: ts-authkey
      namespace: mariadb
    type: Opaque
