---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ts-authkey
  namespace: mariadb
spec:
  encryptedData:
    ts-authkey: AgAa3Rl4bsxnEICsQqUTBq4zHg9/wMrCXZ5oL6/nkXnDVjG6BbYeNIztFplIbMJA0KyiFxvKWATnBg+XmYXYMWTWEgtWx3GsBbs3M08exYSkZJUHzDAUq6oPmtx8D+d6GkNp61tZC4JfQWjw4qnMx1dglZHDgIq+OKP5pKdxeZBaRqHjfilkFdnyMWVpEZrDs51v2/6+0p4aXmyiwmX5LurUNw9rQWf1B2O5RY5nLGDuhqzA6IWH5GhRihPQYpjMJP7JNrqGfj6/8OPqoj57I2Mk0gfCLCRrt18OAWC44CsBNh/r8gay93ZZ3vuE1TM6RyI38HqOxXoPEa7/+s1ZQdmcQnbdjVYosMNOX7zUa6Kub58/nR3xJS97EopW234yMJ5v57BK6iWlYk/fW5cuSFXen+GAwd/Y9kvJ73+kcx3ZqedqhAHxJD9LnCoMGm+BMAHv5Rd1CzNljpk8bsTneLqpOmkrMtJI3s+L39eAfrW1fn6byQFm3TyKRN1STYkEcNepOJJ46AezMkuBLYYctIErI6mp46fYFvQIL1wrcmpQ4yzhQcHuhHVCkkq7xr770pPS6jghiB3iBg3Z2e6+gX3vWjhWr4K1sJ3/nQiQM2Z1Ki0F+0HdSouPyr4DWt0DIttRQzWMW9aKE3yuAVGCPUaX5CdBaABrfktFMgV8cDwCDMa8jtbDfibacQXBNcgmiyPyglLDkh0dFzZMkE/yNjQK9msTlaCiDeQ6ghQ6BYYQlcVyrKJkmAmi6/AmWxs3vVzJmqkDXHlOU1NIUJiJ
  template:
    metadata:
      creationTimestamp: null
      name: ts-authkey
      namespace: mariadb
    type: opaque