---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ts-authkey
  namespace: mariadb
spec:
  encryptedData:
    ts-authkey: AgCMVwq3m1wsvzegkuPmBEbzsBm1wKcfaINLcjpCwmOVVEQiRvkIhvz0wTU6FWWys27Uvo3UrY0Qv6PEFhQO+Wn1Q5VflBfcLhv5hH99wic8x7LXElpU10FZ3ogUN0Uqu9Wt5GEM6z0JCDnHUfQdm9v8hkCvNCCNwH09E09nB/uLrwxNM1s534SdaMGrMrloDW0Zue2bOybgVQEgeko45Oe9qJdnF6d5qlRUDftoPqB8fM2fF9/FXj7eGnZGewp/NEp5umPGmTAr0lABu6RSK+jlgAIgG6nuggCLeQUmVU7WL6cA2Qu11MKNE8tJ1u3xFiYbsWfOOfEWBwWM5GhjGNWyX1ThkecDNvlyggTb2XguocKTGQwCB9SNafgTZhHcdwyEjjp6FV8XtiC56g+jOxVEGFBCZ4OE1KQjhQ7hODnD5RUR7XeohwBC855l5x+wTuoYu7X2I0i+kWTkTrT03TCePS1Pb+cMyAegTYMtku5znJIV4RCyPxhrKJK4FH9Box2hurTesOyQ0+c9HffHhCLRk7vf2jprsO+Ry4Aj1a4Ia+mMu3u/ohDLIQKW7QbB68ZLHJ4xVer6TBYdG5HsjCuqEZMD83AXWeldqaGNRQp2bA13Gz6LXRpa+MkNllS/qILxIXafRUh3riIHL1AHB3mIMdqMg+Hhk5zBcd88ynbw5q0sSkx2diE1EEqIuGXPNOQ97QdrLZ3pe9nJZA9ZAtJynWcOiqAN1xCSxBSdxMB4qpEPWVUmF0iYpdF9Zd/cP0B0sqBgb5xIph0=
  template:
    metadata:
      creationTimestamp: null
      name: ts-authkey
      namespace: mariadb
    type: Opaque
