---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ts-authkey
  namespace: mariadb
spec:
  encryptedData:
    ts-authkey: AgCkgPygc717IRPcBEic8CFyEj7ZTHByHjyPXOPbPydAjzTvEUvc/AEoUOgz2VMeJiiDqs1e9I6cGxdV4BpnXdvu/kadoP+bdKP9ZX0s4aLFkUtpnF65vONO+gRQDJY+ZAOHsvq+y0SQUE3Z0/ZehuKctG301xZm/1gJmOjuWAjlpptho/lE1QcmbfaJ0edBoTMl5WwDmTLFOsJS3B5L/abgI8/cOxNCFWFj5ORt4iO3p/h5fFOjXVrQobPic6CbZ3fz91GbK0khJnkprI8yTGc30fbF/HI3dZic7UWdTyllZxkSbZbCeys1JtAKJCKOMhbkyuU9P0vwg/MRtJRkwS99JBSnQHwDrb+Uzs3LhJjNBEUUZCKrY/d4RRoNbTI2/VEsxdvMa7Xz5JufoJmeBLxgquKkOYq+MnVKWHowywrzjCytfl5mKgrXBbyw1tBsjLWOLso/o2f9bCGkloKe9esC3SXHurVVhvVuIpM2T4f2Zi4hqZpJ7I/2F0+7URGo3hEbGfQsKvhtJkmvhjYjHO22RdOiQAfwfAFXIbqEj2X/9p9/Z2wWmnI5vqWEerJwdHozU+4oz1Nf+9NwYzaIOpO4IRRkjKBJuNMqwy1H61nv9x3nfzgRIZ6i6Q3o3263woy7iotaGK1WzHpACTuq6vVzQ2HhOFm+TwV+FaaVmsenutmEm8ssAkJq9SgKy2/LcFNgnXg7o86KxrFq0AYwn6Thjw7VFXlp+tQ7HqHiKE3rF2RbkXuCQf0djfTDP5zP6/Lg49hC4cUTBnKgKXqA
  template:
    metadata:
      creationTimestamp: null
      name: ts-authkey
      namespace: mariadb
    type: opaque