namespaceOverride: mariadb
fullnameOverride: mariadb
commonLabels:
  networkClass: Database
serviceAccount:
  automountServiceAccountToken: true
auth:
  existingSecret: mariadb-passwords
commonLabels:
  tailscale.com/proxy-class: 'enable-tun'
networkPolicy:
  enabled: false
  extraIngress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
      - port: 3306    
primary:
  persistence:
    storageClass: 'local-path'
    existingClaim: 'mariadb-pvc'
  service:
    annotations:
      tailscale.com/expose: 'true'
      tailscale.com/hostname: 'cloud-mariadb'
  resources:
    requests:
      cpu: 20m
      memory: 300Mi
    limits:
      cpu: 800m
      memory: 800Mi
  configuration: |-
    [mysqld]
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mariadb
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    tmpdir=/opt/bitnami/mariadb/tmp
    max_allowed_packet=16M
    bind-address=0.0.0.0
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
    log-error=/opt/bitnami/mariadb/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci
    slow_query_log=0
    slow_query_log_file=/opt/bitnami/mariadb/logs/mysqld.log
    long_query_time=10.0
    ## Replication slave to Galera Cluster
    server-id         = 03
    relay-log-index   = slave-relay-bin.index
    relay-log         = slave-relay-bin
    gtid_domain_id    = 0
    log-bin           = slave-bin
    log-bin-index     = slave-bin.index
    binlog_format     = mixed 
    slave-skip-errors = 1451,1452,1032,1062
    report-host       = onode1
    [client]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    default-character-set=UTF8

    [manager]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid