---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: admin-token
  namespace: cloudflare
spec:
  encryptedData:
    token: AgAKWbNnBbqSQfX8gdEVERWzdAStyBec/531vRoLpz8sSlfYpuppFyoX6LjovSGRJZJOwO861p84xEEIE8txQb7Js0olnh3rv02pjWbXsXiCQdmOrCYAAECKWUpsjGhiOy2WQZN0IhEZQIA/pPU8mPFOpRsftGJ5iMNPue6fuIColLySwt4LyJ0cVOhBlyPMb87MAjyRTG3Dd1YwBjSz6scXmcnKsVAGVcKNHwjZaBqTcS4A+WIYSjnMkm/o/CvLLpMV0MtXc2vrQV4IOWfN0DrgdvCB0aDdOx2rAaj5zinD4vcz/4oAOy4gq5UXbq+f+fT4BjcIUMHL2ZCOXVCRzSSrfSCBpxZgfQzH9WYb26aaCnHPTeTrHBaS3U211SVqGfHlzNSj1Prb4sC38buEpIS4uzoz5d7P7YehG+/tTWl/iXI1nCgkQt+lzLPxIq2t4eACz4Brmz7swNP6jI4eyywji4RUKFGVscwok5eFQDG3j5OkJbV0t7TItpxcseLozVQ9y6LduWEK9IvElVQQqgAp6nW32jmzNM42JBIeOIVQ9PCBdGdSjo+U+z0wf+UwzrmXoWHowCb2nUXl3m5XDjNrCcMQY3nhGoysCA0mvk6jlA8SFSAnRiN+Fl8/cRqu0mIQJNj1uWp4ccgJUDnAZBSWBGWOynWgdMWwC3d3SJtePq9HurVtK1CGbCOC/3chhOyRgppZiePty7Td/pilCx25m1h1IgWGx0b9D5p3Cfsx/91VB9BF8U5CV95F9cEVFBr11oH0Mkl5x19PxfpfRGT2xg+y1AxT8GcleK9Ebm/FNvOAq5sSURklEdJukCVK//8JAggUmS0n5iC6ahYRQM9L4XLZhGPNw4sF4KTtuwF6ug5NYRK28tPPTV53iZVJSNLPGjdeWyS/+ZZHyBJeQ1hkCoXihTJx8ZL5OxAJPvOGvhIQvURNWt6y
  template:
    metadata:
      creationTimestamp: null
      name: admin-token
      namespace: cloudflare
