---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: admin-token
  namespace: cloudflare
spec:
  encryptedData:
    token: AgA4phqsx4ZBTlQwaFkJwqF6bDQ4Xn99Xy0AfuN4dRECCaRVMfdTnK2y5ar3HHMJc7FG1Xp4OnmCvYU5sSw7opfkDosiUpqLpcmACyLqBUQ4B+KZveVNP+DEkfiJbEUmLvh3BN9uEoJPFEWHqBhFM/Sb7Bp5vpf+zDvkgc29jo+LG6sGEYKSwQ8fpDcfZA+qME4qlbTxjA2YIGqlcpYHczpvAenZpGUEund0TY7uhPX76Dm7GNXv1XvXVSI7H3hwvIasYeoiTjrgC9Za5U/ZhCxfGiKuIwo4BZz+1RTjy2EjBsccxJOhovpJny5IO+n8ohfBaIC0eQ+FfUly7Ke8SA/oJThLHsPHof2UcU4EQm94y9bYu/qUYHnj9WNGyfq8tXfFNU371zPhHD9QN5/uvr18dg4rXXQ98lGwvmpyjFUT0xb0O0MZGbLcGIZsutA8SfB4oYi5aeXihEoGvuxTvTun3TxQ8pYPJ9mGsDKbrg+ezWPU1i/WoNz1il7Wmba7IaUfscS2WfiMt+rl0GtiF1TBkLZnveYXoGvvO+GDXokKct+nDscRyY3UKT5+1erY0dt9v+NtvyVCRplAQsnycrdbxeQ1/exixejqtCsSt3O7ShrVvysys8PX6Lr0j/aRTfAXBjEGHISN2Xo7QnnrVs0pDd989f4ROd2SWlEGlZG8KUYyGCJ8GJUQm2aZscwUHKzx01xF/AH/uwO67aJW+YNrmuog2t2966EdlScY5gxuO5XelFcZ06QwxZps9CjenK65doO24ZQGdQEfsCx1nUPbvnrXawpMHRI3XL5zrenWyxEaMti9A3wssfba6zdHNz2TN+oRUad1i7cm1tXCk+QvTNn1fDRS5gpz6HxVn/2R9f1QC9ED0q3ItxgRe4613qAaEWhA/Kse1cCbhewd4oNmM/hQ6kCL9EA8WccxhQMLzMPZNneSJAA=
  template:
    metadata:
      creationTimestamp: null
      name: admin-token
      namespace: cloudflare
