{{- if not .Values.disableHTTPRoute }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.nameOverride | default .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - name: tls
    namespace: cilium
    sectionName: https
  hostnames:
  - {{ .Values.httpRouteNameOverride | default (printf "%s.ucdialplans.com" .Release.Name) }}
  rules:
  - backendRefs:
    - name: {{ .Values.nameOverride | default .Release.Name }}-service
      namespace: {{ .Release.Namespace }}
      kind: Service
      port: {{ .Values.service.port }}
    {{- if .Values.httpRouteFilters }}
    filters:
    {{- toYaml .Values.httpRouteFilters | nindent 4 }}
    {{- end }}    
{{- end }}