{{- if .Values.service }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.nameOverride | default .Release.Name }}-service
    {{- if .Values.service.extraLabels }}
    {{- toYaml .Values.service.extraLabels | nindent 4 }}
    {{- end }}
    {{- if .Values.service.annotations }}
  annotations: 
    {{- toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
  name: {{ .Values.nameOverride | default .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  selector:
    app: {{ .Values.nameOverride | default .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: http
      name: web
    {{- range .Values.extraPorts }}
    - port: {{ .port }}
      protocol: {{ .protocol | default "TCP" }}
      targetPort: {{ .targetPort }}
      name: {{ .name }}
    {{- end }}
{{- end }}

{{- if .Values.tailscale }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: "cloud-mariadb.tailb7050.ts.net"
  labels:
    tailscale.com/proxy-class: "run-on-worker"  
  name: {{ .Values.tailscale.name }}
  namespace: {{ .Release.Namespace }}
spec:
  externalName: {{ .Values.tailscale.name }}
  type: ExternalName

{{- end }}

