{{- if .Values.persistentVolume }}
{{- if eq .Values.persistentVolume.type "longhorn" }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-{{ coalesce .Values.persistentVolume.name .Values.nameOverride .Release.Name }}
spec:
  storageClassName: longhorn
  capacity:
    storage: {{ .Values.persistentVolume.size }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: pvc-{{ coalesce .Values.persistentVolume.name .Values.nameOverride .Release.Name }}
    volumeAttributes:
      numberOfReplicas: "3"
      staleReplicaTimeout: "30"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-{{ coalesce .Values.persistentVolume.name .Values.nameOverride .Release.Name }}-config-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size | default "1Gi" }}

{{- else if eq .Values.persistentVolume.type "nfs" }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-{{ coalesce .Values.persistentVolume.name .Values.nameOverride .Release.Name }}
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
spec:
  storageClassName: nfs-csi
  capacity:
    storage: {{ .Values.persistentVolume.size }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: 192.168.1.3/appdata/vol/{{ coalesce .Values.nameOverride .Release.Name }}
    volumeAttributes:
      server: 192.168.1.3
      share: /appdata/vol/{{ coalesce .Values.nameOverride .Release.Name }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-{{ coalesce .Values.persistentVolume.name .Values.nameOverride .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: nfs-csi
  volumeName: nfs-{{ coalesce .Values.persistentVolume.name .Values.nameOverride .Release.Name }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size | default "1Gi" }}

{{- else if eq .Values.persistentVolume.type "local-path" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ coalesce .Values.persistentVolume.name .Values.nameOverride .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce 
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size | default "1Gi" }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{ coalesce .Values.persistentVolume.name .Values.nameOverride .Release.Name }}
spec:
  storageClassName: local-path
  capacity:
    storage: {{ .Values.persistentVolume.size | default "1Gi" }}
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/var/{{ coalesce .Values.persistentVolume.name .Values.nameOverride .Release.Name }}"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - onode1
{{- end }}
{{- end }}