---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: emailupdate
  namespace: ucdialplans
spec:
  schedule: "0 8 * * *" 
  suspend: true
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: emailupdate
            image: docker.io/curlimages/curl:8.13.0
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - echo "$(date +%F_%T) Checking rulesets for updates..." &&
              curl -o /dev/null --silent --location --insecure --request POST "https://www.ucdialplans.com/EmailUpdates.aspx" --form "userID2=$MS_ACCOUNTID" &&
              echo "$(date +%F_%T) Finished!"
            resources:
              requests:
                cpu: 100m
                memory: 300Mi
              limits:
                # cpu: 300m
                memory: 300Mi
            env:
            - name: MS_ACCOUNTID
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: ms-account-id