---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: codesign-cert
  namespace: ucdialplans
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: codesign-cert
  dataFrom:
  - extract:
      key: /ucdialplans/codesign-cert
      conversionStrategy: Default
      decodingStrategy: Base64
      metadataPolicy: None
  data:
  - secretKey: keypass.txt
    remoteRef:
      key: /ucdialplans/codesign-cert
      property: keypass.txt

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dockerhub-creds
  namespace: ucdialplans
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: dockerhub-creds
  dataFrom:
  - extract:
      key: /ucdialplans/dockerhub-creds

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: credentials
  namespace: ucdialplans
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: credentials
  dataFrom:
  - extract:
      key: /ucdialplans/credentials