---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: env-secrets
  namespace: vaultwarden
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: env-secrets
  dataFrom:
  - extract:
      key: /vaultwarden

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: env-email
  namespace: vaultwarden
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: env-email
  data:
  - secretKey: SMTP_USERNAME
    remoteRef:
      key: /email/smtp2go
      property: username
  - secretKey: SMTP_PASSWORD
    remoteRef:
      key: /email/smtp2go
      property: password