replicas: 0
image:
  repository: vaultwarden/server
  tag: 1.34.1
  registry: docker.io
priorityClassName: medium-priority
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 2000
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]
env:
- name: TZ
  value: "America/Toronto"
resources:
  requests:
    cpu: 1m
    memory: 60Mi
  limits:
    # cpu: 200m
    memory: 150Mi
service:
  port: 8087
  extraLabels:
    tailscale.com/proxy-class: "enable-tun"
  annotations:
    tailscale.com/expose: 'true'
    tailscale.com/hostname: 'cloud-vaultwarden'
httpRouteNameOverride: cloud-vaultwarden.ucdialplans.com
envFrom:
- configMapRef:
    name: env-vars
- secretRef:
    name: env-secrets
persistentVolume:
  type: local-path
  size: 250Mi
  mountPath: /data