fullnameOverride: sealed-secrets-controller
keyRenewPeriod: "0"  # Disable key recycling
skipRecreate: true
secretName: sealed-secrets-key5l82h
resources:
  requests:
    cpu: 1m
    memory: 9Mi
  limits:
    # cpu: 75m
    memory: 15Mi
livenessProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 3
  successThreshold: 1
