---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ts-authkey
  namespace: mariadb
spec:
  encryptedData:
    ts-authkey: AgDDjMn8XWRfN2WKNqoOBiGrRT9mKCkoHr8IF4iKxl4GlDS5K/TuPqIX2vxzuHSEBbyIJleO2SD+eAVrTeNl81CbqM00+MF8p1lS6HgaqreRhkgAvcM2qi3Z/HHV7YS5AbMymaeY79VZfaycjEjdLfQJIrW9MBWTeX5ZVJCZieiCoaXeOGx69fhBefm7oZlxgYgGXCoYwLsc2z82lMx5Ub9OylZPi9BVdO//0xJLsI4Ig/DXtvjaPxv5X3H+IFOf52HR/66e2zJ+E4Ut9VjJ18knbN3/AHBdytUcCfylvphsc5JwxWae9+k15C73RKK5KJ/JPKcQ3hh7j09IB/zOXZJwoxTbJWudkLP5RUyOgbmaxnIXEaGqkotvo7m2Ei6EBZ9eQL03FHkfbY1orG60dS+Vmk6QHVRqFGxxNX5ntf56gkFi1wOT4ved4Ifj6IFKD6TMq8vp97fFIhJqLq8YFr3QbwxXyy+yjUcC9H7+zIMBdWb4XtG5F9EcdKtHt+JZE4zCZ4LzZa9BBamJUBjI0eGq+/yOEnRTZIc2CJfQWGRuwGmrRNHdZqUaLDZi1uwBCK4k3EpWztZmqHMvtXctlIBB5QOhA61MQd/XnTpUOEkH91niJEamL1768InJjtwUJfW+9v4j5RQiRH5ns0YZuJ3kwzGsDQljcZ2Xd/USRUKFJudGUDvLPZ88Wj7kHymippSsekCpcr6Wm9//3iAIi66Va2N9npAaCfHcX6omTpXCiEWrY0K8RgsCQqlvnD/zxH4tzxlo4zHnTpRYVZ3R
  template:
    metadata:
      creationTimestamp: null
      name: ts-authkey
      namespace: mariadb
    type: Opaque
