---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-mariadb-backup
spec:
  storageClassName: "nfs"
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    path: /backup/mariadb
    server: kenlasko.duckdns.org
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-mariadb-backup
  namespace: mariadb
spec:
  storageClassName: "nfs"
  volumeName: nfs-mariadb-backup
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi