---
# Installs the base apps (Cilium, Traefik, ArgoCD) to get started with installing all other apps
- hosts: workstation
  tasks:
  - name: Change kubectl context to cloud
    command: kubectl config use-context cloud
  - name: Install default sealed secrets certificate
    kubernetes.core.k8s:
      state: present
      verify_ssl: no
      src: /home/ken/default-sealing-key.yaml
  - name: Install original sealed secrets certificate
    kubernetes.core.k8s:
      state: present
      verify_ssl: no
      src: /home/ken/global-sealed-secrets-key.yaml
  - name: Add Cilium chart repo
    kubernetes.core.helm_repository:
      name: cilium
      repo_url: "https://helm.cilium.io/"
  - name: Deploy Cilium
    environment:
      KUBECONFIG: /home/ken/.kube/config
    kubernetes.core.helm:
      name: cilium
      chart_ref: cilium/cilium
      chart_version: "1.16.5"
      release_namespace: cilium
      create_namespace: true
      update_repo_cache: true
      values_files:
      - /home/ken/k3s-cloud/cilium/values.yaml
  - name: Add Sealed-Secrets chart repo
    kubernetes.core.helm_repository:
      name: bitnami-labs
      repo_url: "https://bitnami-labs.github.io/sealed-secrets/"
  - name: Deploy Sealed Secrets
    kubernetes.core.helm:
      name: sealed-secrets
      chart_ref: bitnami-labs/sealed-secrets
      create_namespace: false
      release_namespace: kube-system
      verify_ssl: no
      values_files:
      - /home/ken/k3s-cloud/sealed-secrets/values.yaml
  - name: Add Cert-Manager chart repo
    kubernetes.core.helm_repository:
      name: cert-manager
      repo_url: "https://charts.jetstack.io"
      force_update: true
  - name: Deploy Cert-Manager
    kubernetes.core.helm:
      name: cert-manager
      chart_ref: cert-manager/cert-manager
      create_namespace: true
      release_namespace: cert-manager
      values_files:
      - /home/ken/k3s-cloud/cert-manager/values.yaml
  - name: Apply Cert-Manager resources
    kubernetes.core.k8s:
      definition: "{{ lookup('template', '{{ item }}') | from_yaml }}"
    with_fileglob:
    - "/home/ken/k3s-cloud/cert-manager/cloudflare-cert.yaml"
    - "/home/ken/k3s-cloud/cert-manager/sealed-secrets.yaml"
  - name: Add ArgoCD chart repo
    kubernetes.core.helm_repository:
      name: argocd
      repo_url: "https://argoproj.github.io/argo-helm"
  - name: Deploy ArgoCD
    kubernetes.core.helm:
      name: argocd
      chart_ref: argocd/argo-cd
      create_namespace: true
      release_namespace: argocd
      values_files:
      - /home/ken/k3s-cloud/argocd/values.yaml
  - name: Apply ArgoCD secrets
    kubernetes.core.k8s:
      state: present
      src: /home/ken/k3s-cloud/argocd/sealed-secrets.yaml
  - name: Apply ArgoCD K8s resources
    kubernetes.core.k8s:
      definition: "{{ lookup('template', '{{ item }}') | from_yaml }}"
    with_fileglob:
    - "/home/ken/k3s-cloud/argocd/[a-h]*.yaml"
    ignore_errors: true
  - name: Apply Cilium gateways
    kubernetes.core.k8s:
      state: present
      src: /home/ken/k3s-cloud/cilium/gateway.yaml
  - name: Apply Cilium resources
    kubernetes.core.k8s:
      definition: "{{ lookup('template', '{{ item }}') | from_yaml }}"
    with_fileglob:
    - "/home/ken/k3s-cloud/cilium/[h-l]*.yaml"