---
# Post-install work
- hosts: k3s-servers
  become: true
  become_user: root
  tasks:
  - name: Copy k3s.yaml to .kube/config
    ansible.builtin.fetch:
      src: /etc/rancher/k3s/k3s.yaml
      dest: /home/ubuntu/.kube/config
      owner: ken
      group: ken
      mode: '0600'
