---
# Installs K3S
- hosts: k3s-bootstrap
  become: yes
  become_user: root
  tasks:
    - name: Install K3S on first host
      ansible.builtin.shell: curl -sfL https://get.k3s.io | K3S_TOKEN=***REMOVED*** sh -s - server --disable servicelb,traefik,local-storage --write-kubeconfig-mode 644 --disable-cloud-controller --disable-network-policy --flannel-backend=none

     