fullnameOverride: postgres-controller
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: DoesNotExist
        - key: kubernetes.io/arch
          operator: In
          values: 
          - 'amd64'