apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: "git@github.com:kenlasko/k8s.git"
    path: manifests/apps/adguard/overlays/cloud
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: adguard
  ignoreDifferences:
  - jsonPointers:
    - /spec/externalName
    kind: Service
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/enforce-version: latest
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  info:
  - name: "Website:"
    value: "https://adguard.com/en/adguard-home/overview.html"
  - name: "Documentation:"
    value: "https://github.com/AdguardTeam/AdGuardHome/wiki"
  - name: "Repository:"
    value: "https://github.com/AdguardTeam/AdGuardHome"