apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: "git@github.com:kenlasko/k8s.git"
    path: manifests/apps/headlamp/overlays/cloud
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: headlamp
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: restricted
        pod-security.kubernetes.io/enforce-version: latest
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  info:
  - name: "Website:"
    value: "https://headlamp.dev/"
  - name: "Documentation:"
    value: "https://headlamp.dev/docs/latest/"
  - name: "Repository:"
    value: "https://github.com/headlamp-k8s/headlamp"
