---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBy+T+N7PyKf11fQR53gGN02m4GhllK7a9T5GC3+KFU0IWXGbrJSsN/oXK2fPtd7HH6gd06zirdWIP7Zs7bBGCGHviKlKCTzUOh6uozR4qRzoWMsKDLLobeEcwfLOEdNxDE4nn3j9Rnk57Ia/uBDbSdmHscnRBh9nKEEjMnaqWz12AwnAAXkCJj80iCR2eYkXqXPn8fp5XzUt9pSjKcl/qVnoiG/dOeKhhwlk/9ZgDpng8QVkt98TZYsNCds2nHX2+u6RNMnzvyA9HruHum1vEuOFJtsO8Yqkz70eDW6Lu9ZnJvmy+3MC9f/3UQyiTanHwr+LYhwogB4l46uaZCb2RCQh99uCxvGxAJ5w+rKuu7Gc7TBJAOE4PAt0VS3sEDFf+Q0q4wToCCaKQ+kHQhoJa0tcH+2/7H5HrpCMJEMWexDmIBEpfYqHqEsKQURuqaBhOXMuMSy1HosuDgslLKUBU9S1aK5WQowZotBiItKb+nX6NvqrN4W4yct55axX9Gn/gW9W1sg+UiL1abhUnoQRUuLL/XY1IhS4u5y21PM+mwWGrVLIRNfLCNlx/Ox+dJylIqaNf/ShCAYL/A2WkQqrRgWL6OitghiwtHhb2q48eDcEEicCZwQzbGkuM8Zil2npcEp+7i6RiQbYkXP/2bW0oWngkypN/d++VrZHIiFD8OgsCAtpvzyBy5nA6OyUytYgJHAU2F7/PKsYCjZ9ZC78zi6NCeCSYMrLCWSMa2W9n6wgudm8MW5FbF
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
