---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-access
  namespace: vaultwarden
spec:
  encryptedData:
    password: AgB7Islt6zBPqwmNGlqXX1zYczL3JXtl/xlIkPgvcruJkWntWoF9SCPEA8gHio2MEleoWFZIcF/svZh8WojAUgA6IEwO9rPIOEZG3qbr7J8bqkjbATuKt5aO4fsFIkFtVHT0N10KqN5xSz7Z1p3hABj9YhnopOvhF4VxFscQxX0vNf4zXwHtuQjUwPPJNyzvDAsUXcCqHaL+ztzzGfub82ZdmMqaytR8fWi+VM43c9yOor18mqxT8UZ24K0uGRMNc/W7LAi6sqv9Q3o/USWd5KYGt8f01SB+MbN5QDG5O3p9sgObPoA4TR0oUGTZYnBMiZrzRzPEIPICs8AjW5gRdbpUwCA+ezJld5FvDfaEE1zg5ns3KRtOP8CmvSsWUWA6dL2zRuTygrQQD87B6Ngepk1WkPGVfAAtctTSR+1AsIQkeijXI7dB/+o00j/AIM6rNipNChSnkdM7oMpIsECIYJDL+2NHqjECkmMbY50OIUFKb3D1yBZRjSGjTcOcsbM3pPqZRGynyWblkm1NIia3Uy6tViDVFDyVmjny+M6/Vk1youejeeTAoiH6aFPfg5CuPfzmEc1Xf4v43DoXBieQDS2Qy9hRAgeLX9rQ7n+q9jHWBI5eBvgNGzdv2SZoKUjCRDYnJmpEss3msmDYvl8rkiNGxmWhCsMhfWGAIH+Nz0X4nXPpbB/9nEotUYy4HaVw9hd4UduSydyjMSFWLN1YJZdvNv8sFVaBjqXtMw==
    username: AgA+4xkkAtXX3wl6L8BpJn8zAM7CWHpH8YAiavmekbV3I2S4gxJlc/h/JOiy/C0BrTiwTc3D8aCTmSS/6/86O2NRlLUbvoE/Tcec/Z/zG+wjNEUEseSb+pDoUCsi9AkYgTj70TUTtFXXroYQ4aim/bncAjy2CleG4JbtjrNB4o+9mhnrC+B3Pmxlxcs0Z3FAwC5eoyFaGWpZBI9fwh02BknXbPiK5+6ev524ibgxT/kfU7GSf8hpHDkrXR8Ud4pHH/eTS9rQSIvMwzeq8DMsQZyhAe9yuA1kphKz/TQtRTPaw0AzBfrT0kX1dS/aLWkYsvj0E6HWgN2vPjAg///qn8qmMzv33hogHRudH8XdhwzrQ8k1gIU0egy4blxbeH4GsJZR1+JOpm2X6OFyvTIvls/GpBIfdl6JXqUdALyR8KsKM2/zc+7NREKCK8qFj0yhE7K75Yw8zDjYPyVKDYZfnWoK8Vv3cLxjhUl4RPI3BL5MthXfNSLrdeuUV6g91ZRiDDXIvzuClgWth13a7nbkDxW5Lsfx5r/dDEKPVtR8Gd1TQg2bjaHaMcNBbUv9mzRcx8M3mcgvDwx3w4B6oZNjGaCU3B2QGsIUGqPxNxJf/HemjdVBPcQwaxVH83hAGybjPo/cCbfg6CUKb+bHfuX3eSVzHxSsUdrYXTW+Mdbgt3Y5Z/d2Pd8VaLIAV9CZwoirOtcchVqkdsPzMbDSXw==
  template:
    metadata:
      creationTimestamp: null
      name: db-access
      namespace: vaultwarden
    type: kubernetes.io/basic-auth
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: admin-token
  namespace: vaultwarden
spec:
  encryptedData:
    token: AgBTdCIIcfrwjVfs9cXrWI5X0rl8Ry5ezz3UDZMwKnVXZtKbF2ZM2hPt8bayiWe2Iq0ReylDIUXUh4uw9GxFJV4xVpDLPqxUWa0SAZ3dDz/VUo2Pr7EH+kbJ0DBvO4nIrefU5kfbSvdTTxOoBh4qFsX1/tTOQJsOk3F9pOrx6fvsqWTud3Xr/kBYAi7TSIvxwIqhj35E5AK6FCYnnVhbMFukgybJgQ1cJA/rEvIM4uvrFLNLmmE0wezQ55/17tQX1vqs2LIXBdQczrAyk9DmalCL0otElIvCY0vd3PCWCKj9L6HIsXpCEfAOiXFGhJp1DvFlyzBMVQFkHpwDKis0vAJoDALqDugV5gYkQ2ZOuOz6MymoHQkWlN4txZP/5TmEBK09XtXZ/KPmn9kztmZv/4lLVGL9Hp8fm5tPeH9kpjoZVeJeyrGEs4F9EZzuiCxWodXFMZH/ZLt7LG0Px/3dqnJnzLy11ojig02/Nv9CNafu+in6KOFGX+IUH5hu0Xg4wajK/o34jMCDiwtHq+vTGAfz4C6kwyWtg2+VZzRJZJhjwhxgeJU8s5/eic2C4UYq+mE5yKDdSwn3zOydsnV+Cngi0AmPFwm7aVpa6gm1Pn/8skv32kkLqnrDU0NHu2Hbofy3+J2j4fOfEVIZRd3Uo08mD9dDJTgLRByyqJ5VxfwqFc06lBzCiVfz1+5u2bRnDaSaiSLYhHOsscwDrU0gWTit/KzgdtuHuV+xyyQeHLDpIdpZFWzE3Ot29Mz9HQxwCoNFJwbKcpyx5p7d8wGO0O6At8AH3Q==
  template:
    metadata:
      creationTimestamp: null
      name: admin-token
      namespace: vaultwarden
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sendgrid
  namespace: vaultwarden
spec:
  encryptedData:
    password: AgCs5umde+xaXpRiTXrOYw7+bQ3Zqd1P0CKjscrdXQeqT2pextZzFwyEKg70+5TtKkBLIYyLezjRZmTSj75zZlK5wnOe/PRnqsFKIZPodJyIJ4nSuZdmW5qWEFQ8y/PLUzyFSfF7zo3RLBP8o3mvJWzfi2WtE5fbW8e6MUlMtRbBNsGdNhgC64wzjFTo0qDzOey908fcNF9TTf/LRhL9raAfvEQq9JM8EcJgCpa+uM8ol0FFENB2AGVUZ3n5jBJ6fAnsnjIJx9/pBcLrLLIcWW151VZyfvpLGNavxlaT4ed8NiSdCmzz+l0NU2ed72pdTO6Qm2NT/ANK7bp5Tebx8V9yvdYpURc1mw/4yNiy8w0OKwspciV+HT+v8sV3HBJ7czi4eWjRkJe+NnEI2lPT29mk3/gV6PqVHQMiBfbns9Hganmd4SVLRiHFjDNlWBcfS2Yh9sKk1JG11ae0HR2OJVNUWi+/D1bqAADLrHcTmx32fPAe+qvDUJJ2aruLrzh0thlOhJsKX1xvxHFr2zPUBrMvG42NQYmHiZnn/s6EqHlQ24stmc06f2D36NaBUrL0gNuknYZuAbawW5n9I61V3tzd+7xzKl02NmuXHKKjQCFOdZLwkoBnGXVO095jDUOPE6IyjlXLKHKqlAOkHVNq7+TOGxuis4uldEZhLQwaaR0RZeuNzVXO94/XvXdsr8LYJiR2WcvThmfnG44DAvAR7VyRlXO0AgTDgZYJrmLwoxxl2QmF0FX3GUpTQamoZbt6lSZ815ivJgJarLGV9oCVvdus0P+8c7k=
    username: AgC/pnWFt0k2XjGaazDMSbAAY6p4V+OFgCVV7o8z5D5UbCZxUq2OaPHl7BYf1mQhT5Zz8nHrV8J1BYKCcdTB2jrLauk6Lbr9lMQlxOaeMZZ+cyo41OFy8jLgDSkaXDOAkgxqwiGIG4bXEMBhhRu+7RC23MlS/kzelk7ZnLNLIrzYse/5227NMjU9HKq6wejxmems+yHl2udv7a0tdL51walVzsyFun1602Lpf7Mro47nNLr9aOGqv+fZMbYouevWnwwhw4sOE1mqsmJIBo1cxAGoAQDtOmkey4kk/MI+Q6ZkEIWOpvuAG0DIK6BhNnrqb0Nj6JjzyR1VbDtjKe1fMcgc8VBDFcP9Mqw1o+ibRV/6VZUi7ZO/Knsc467FId52MvpjiQbGsnixmqHtxwHlIhSZBGC+ASzrx0/JEI86NUKHM1q4HoyFmzRIu9YvkKNHzhogpywdS385XHCIc7KYCyinV0rtzgJj9Of3f7FT0j/Y/APpc5e9O+BUCIezVM/mGKO2+HIr8JxN9fYBuextZyCuSY4okyaUsuPhm1BnG51cJZcpjG+pnQ8etBOGSAmLY6LbRF2sawLJROM7MY2cY4PJGQKTu0dSMmqJSZdQgKCC6SjVZWHWc58qE1es8APXWBSGndTp7va4kl+pVFbxMhhamp0s92NZ38JI/Dk+ClD+affLdgIJI6XPSn6FbSZZOCusYUIRNpY=
  template:
    metadata:
      creationTimestamp: null
      name: sendgrid
      namespace: vaultwarden
    type: kubernetes.io/basic-auth
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: yubico
  namespace: vaultwarden
spec:
  encryptedData:
    client-id: AgBGpf3ijTurjWTBqrX1Ml4Lkekm61ZtuNv1RnYovDJARoRxgksUb+61VxENvHDamU3bdX7y9WxtQSFIIu0zslBFjUyNJXJpaQabRgWqsHUAJYol1aHE+00yn5Ou16q9Gj2uE9PP/prVpvSsi9EOfvyeVyaucZaix2dCueP9qZjuVA17U8mylDddHPSQ5UCZHp2GsIX7/8SOdphni1ONiP03sk+rbYiwWLxKWZ7IMNWChyCyeeAitTKoqQpfghlmImancrxi6dIf0BEDiCrX3xtTOWucHEN5jfCK8zGYLCpmMVpoj1/zqCr29BuoTRy6zWDIKjfjGEDwK+5RJsMM/bR47E8iblfCKi1QGfAo0+JsKrotH5HTp1Kn4bteZ50kZQRIAbhOkZ4tQZk/8Z1UFmY12va1HX64JlqNmI5eFkio8gsL/hS1WcLO5iiaF38z9lUnv7w6rYCeaDRqBdlnloael/eypTuZlQM/nGH/U0uybovnevBoWrcG6KYlXO5si9Y/kyDQ4jrsy5q7wC8hu87InGxM+xvrdtQjvTmvlQQ2O2H5IeNuniNHSlYx8ZBgU8+y4WGBRmNorEUuZs98Ivh4l7wJAUj+HgCjUWVE+nXf2owJxWW9vfDkOeTgzHSwfvzXp/e1VLmwnaMw3rIYsNxSwyTVuqxAcDAPtWovaktosrsny/CD/6n03P+6hMYm/Z5y7TpP6Q==
    secret: AgBx1v1WCGX7WZYHgHC+bIEShmR+u3EK6ZFCbfC+q3ZuFFK2RtuAfHlog+Y4n2SXT1OmTDwRiKpDVt96K2YAHVSBCajKhptJfxsGr1CaeISFEB+0AHL8N5R2zx85id7L2CCnNwjTzC6GkWduzIYT5VBf+K2qFT2ClMpoCNHpH5Hy6RaRGSxZq1YhF2b38Mrkz/IODgvI8FhP146tv+uZVq9PefV043tcRN3K7StKXZjlf2SiwkzdbZAt9n4i8SjtOAnPH/yholVAvnijsazx0tw0NszQ5PH3lqpnI9z+0BRGUIny9V0se5zvgJxoyBWQU5TfGggi8LK4Q8g2obtVkG2vW99AEPH8eq0qhSU4rrL7krk6nKy8h843BI8yhNf+4o/9ob+ThKEi5FVTEqwDjjzMUxo0vhCf+iHBe+FYJU9weHb8pzlvmkmqzk/nZiFtd6SnK3PEN0fR5PYCwseLauyXgze99U3dFhzBRJsCqL8imaGUe2nWcPD1ExaYBlxpQxySediLaQHJq9AZYBgs6Nx+i7FXoZeUJcwWokGmpijLvgBA0pwohLE/7tD+GRGkPRSejU/ca8k089EbWPVOlW2SzBzkNMEv05oFlxCg3rNSJPdJpQIuawGwbetollq7XCbdy1VDZFMWuXtNaT8P7mNlszoG07k4N8VNMAmlx/4ubqFn4m21gBWANIBZ+CAuP2so+wCY31sHLDXS31btYFcNyHuglfyNjO6vyxCC
  template:
    metadata:
      creationTimestamp: null
      name: yubico
      namespace: vaultwarden
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-url
  namespace: vaultwarden
spec:
  encryptedData:
    url: AgA8wI7NqwYt3JX2ZcpbecZ8gRlk8nxWZCnelDUmWl4Z+48N9KuG+gobFd4GYpyjTjRYI56X18SzALELaa2CtcI8nKNH4+3MWFok89ki7+hO0zLZ8uZ2akokN8Lyzkuel9v9A3EG9O0GtUULQvyNQR80Cj7mPO1AcTtwFdcVuLJgkSrreJILnoq2iac279Q+Lg3BUf/pvcyG+kwnDfnc50zvTVzS0CbHbT0RzjWONBt2jcAOi5fbLLKKb1hqBIyG1009z8Nfp/C4ZMAm6M5kk9U68KKiZIMyqN3KMo7FJvjvAtPXt6DlcI/s6wjtrKFmb9hJMoCk2DJ9QPDjzGW8gtJVm3g6kLzV6Rwl1rVSsMI+hVHo80geYFextz7OpWlsU6+15jNe5G7tT59Ie1F6AApXJXMvz+1T4NPQZo0XS9KP/gnDvT4YKSBSDZcRL4agJdA+5FEYtpElnwWYroVw4marFQahofJCP1dzJVEYnGb3lzOEq/ziSvmbgDxZ3Nnq9jTDgNprZIVwHcyyYmTn/BZYj83smHrhE2J02fL/K70Yd0wS9sW2nGZa2F+2QKlxnBpFoMTszeNQc283mPyhzdgLgXz3YSWWGmkAuqgJcQTQ8hOkqti7DHtgoH/7+0P6rfO4lVlRR0n9v6XV0qoTkgD5mgTy4QAslDjoPO2tXmfsoDhaYSXUsGcaYV46oCHs1paEvlepzUdxMj8gza8A2ClMy7ZZ0f8l9+sJZK/LlFEPGuK1xAA5rM0T4d7B96VrjAMqrtEPrCFkjuLkQ4GQRPOnviFASvrI3CBm7KB6wMs+2S2rpnGJqdaY3Bv1pw==
  template:
    metadata:
      creationTimestamp: null
      name: database-url
      namespace: vaultwarden
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: push-install
  namespace: vaultwarden
spec:
  encryptedData:
    id: AgAt0Jsb77DRvUVhDEEVBTHq3vtKLakaVylAxKOboZeCGIsvtr/HrvVNPlR7iKLANOBpsxeh+F4DVxPq68IbjT3aXN5Qkp2C5KEkUMBga7ZpRKlcO72BvaqzXHhG66Ei87pLnStJ4wI/n7j0oKKsJu6NrLRhpdBqEaPQPPH9t7TrU51RRSgCrtR9wD9cpRBLYG3hkdIDVcSw3KEWQ07GpMRZ11Qh+hDy6Tk5wWoGsW3GXUApX7XRxwTsj0x2ciLfPKpLAAyuDwniFgo2RQ4a/3B1RD7AOW/BcYXuzTdgRJBP3hHZCqOJ++BGWnN6p3qbj20nCb+DgWwhiRADoooy7BSqIePXW6MWloZ0bNYNNAcdu14NjMSFtnI0xw6cvMfLnB73lZeZReeNIefWLPfTxJGjCdxMLRwLosVqziLVvcuWNy+g+6NYjteRsmddxPZFDy3Qoo9Zb1VMtWgS3fgrt3auO1Q6iRNoKIy1ne9nFn4wx7VOSZ7b7EQGgwxw7JRrPFKDi3lCRHcyX8GGv02YXYzWUxWZZNLBlPQIwttAdmPk/yzMphTnGowfU/pwH1WkA/7tPiBPAPg9BXrHVCyT6OVzEN6JT+xi9GgCY1nhrGZNBx/L0FUfNVomcDOaMBwQkHrQey9aIP9KZIlK/BlULomDfuPb70t4nWH8ucmB+Fkn18s0FucBJrpX3V0DSgtKTTaY5UotrgcMEnUgbUBEObXAzNsCLIt5c6bM9agsyvNuypnZAdY=
    key: AgC/L0QYVpKlmOQjaujJYsZaq5P2amalxrdr5i0aPPna+7vqF6gMXAXq8ypo7/Bzs6UJK6FmQ6PgE5ghnRYiCPLn9I3s1wMuoDkMBCaH/ZkAiHT3PIUp9Nw1ka0MVXBJul+kuQVJ5rK7XQy/4cJXZJprwU0h9G2ABXWsefnBCXAZvwUjUPHlSe9knbAfj5QMSzmCYYOvnuIQ65mu50efAzmJo1Dk13BgSiZAIn2mxYEKUPbBeN06zRaUnsx0N38wSt9fMNakiH+vw66+tT+LvXTGhgHDPfss9CUPnRV/4KBH+JRjOkd4LkidwQ8Ay4ib0us9+e2VabjUIlufl+5b4Zi+gNdBS38I4Mjc1BLJd9msg4Mj0LX42m5qb9JymVurPsyWQj0QjRVbDDRCyVnrbqZjbKuAvHSk/LO5i9tgPkhsbRckBiO23wxwMYgbs4bY+uV/KyV1hL2HIoxOb4T96RaKupR3//CNbXJF+OyzyzG+VWtDuOPtsy0hDSI8FH2WEcI67XQPgu7PCL4gAPDOwQ/fxF35ny9N2Q5U6xwF4LmaNnGkXdB2tDibiYsRYthenIkhZM5MKRaG3lp9w4xXd6fhVWZDGuLBKakDKmMQLFwWDbY+y43mQxsuytwiBEZmvmkkqx91+dad0i2yqK9KySpBewC1KvTlaM7emPbd4nL8ogI1sX6OLiAloI33hAYEDc9U8PLiwsG8/BF3bvOZz3z/QhBxaw==
  template:
    metadata:
      creationTimestamp: null
      name: push-install
      namespace: vaultwarden
