apiVersion: v1
kind: Service
metadata:
  labels:
    tailscale.com/proxy-class: "enable-tun"
  annotations:
    tailscale.com/tailnet-fqdn: 'home-adguard.tailb7050.ts.net'
  name: cloud-egress-adguard
spec:
  externalName: cloud-egress-adguard
  type: ExternalName